// ============================================
// LaserCAM Pro v1.0 - Language File COMPLETE
// 11 Languages - ALL keys translated
// ============================================

const LANG = {
    // ==========================================
    // ITALIANO
    // ==========================================
    it: {
        _flag: '🇮🇹',
        _name: 'Italiano',
        
        // Sections
        sec_project: '📁 Progetto',
        sec_machine: '🔧 Macchina',
        sec_home: '🏠 Home',
        sec_import: '📁 Importa',
        sec_vectorize: '✏️ Vettorizzazione',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Editor Path',
        sec_presets: '🎯 Preset',
        sec_objects: '📦 Oggetti',
        sec_properties: '⚙️ Proprietà',
        sec_jog: '🎮 Jog',
        
        // Buttons
        btn_save: '💾 Salva',
        btn_load: '📂 Carica',
        btn_save_profile: '💾 Salva Profilo',
        btn_set: '📍 Set',
        btn_go: '🏠 Vai',
        btn_import_image: '📷 Immagine/SVG',
        btn_add_text: '📝 Testo Raster',
        btn_add_vector_text: '🔤 Testo Vettoriale',
        btn_vectorize: '🔄 Vettorizza',
        btn_raster_gcode: '📄 G-Code Raster',
        btn_delete: '🗑️ Elimina',
        btn_delete_small: '🧹 Piccoli',
        btn_new_preset: '+ Nuovo',
        btn_select_all: 'Tutti',
        btn_clear: 'Cancella',
        btn_start: '▶️ AVVIA',
        btn_pause: '⏸️ Pausa',
        btn_resume: '▶️ Riprendi',
        btn_exit: '✓ Esci',
        btn_send: 'Invia',
        btn_copy: '📋 Copia',
        btn_download: '💾 Scarica',
        btn_send_machine: '📤 Invia',
        btn_create: '✅ Crea',
        btn_connect: 'Connetti',
        btn_disconnect: 'Disconnetti',
        btn_stop: 'STOP ⛔',
        
        // Labels
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_mirror_x: 'Specchia asse X',
        lbl_mirror_y: 'Specchia asse Y',
        lbl_threshold: 'Soglia',
        lbl_border_margin: 'Margine bordo',
        lbl_remove_borders: 'Rimuovi bordi',
        lbl_resolution: 'Risoluzione',
        lbl_bidirectional: 'Bidirezionale',
        lbl_objects: 'Oggetti',
        lbl_width: 'Largh.',
        lbl_height: 'Alt.',
        lbl_lock_ratio: 'Proporzioni',
        lbl_rotation: 'Rotazione',
        lbl_power: 'Potenza',
        lbl_speed: 'Velocità',
        lbl_passes: 'Passate',
        lbl_name: 'Nome',
        lbl_text: 'Testo',
        lbl_size: 'Dim. (mm)',
        lbl_lines: 'linee',
        lbl_bold: 'Grassetto',
        
        // Context Menu
        ctx_set_home_here: '📍 Imposta Home qui',
        ctx_select: '✓ Seleziona',
        ctx_select_all: '☑ Seleziona tutto',
        ctx_duplicate: '📋 Duplica',
        ctx_delete: '🗑️ Elimina',
        ctx_center: '⊙ Centra',
        ctx_rotate_cw: '↻ Ruota 90° orario',
        ctx_rotate_ccw: '↺ Ruota 90° antiorario',
        ctx_flip_h: '⇄ Specchia orizzontale',
        ctx_flip_v: '⇅ Specchia verticale',
        ctx_vectorize: '✏️ Vettorizza',
        ctx_raster_gcode: '🖼️ G-Code Raster',
        ctx_edit_paths: '✂️ Modifica Path',
        ctx_gcode_vector: '📄 G-Code Vettoriale',
        ctx_simulate: '🎬 Simula',
        ctx_frame: '🔲 Frame',
        ctx_go_home: '🏠 Vai a Home',
        
        // Modals
        modal_new_preset: 'Nuovo Preset',
        modal_add_text: 'Aggiungi Testo Raster',
        modal_add_vector_text: 'Aggiungi Testo Vettoriale',
        modal_gcode: '📄 G-Code',
        
        // Tabs
        tab_vector: 'Vettoriale',
        tab_raster: 'Raster',
        
        // Simulation
        sim_title: '🎬 Simulazione',
        sim_pos: 'Pos',
        sim_progress: 'Progresso',
        sim_time: 'Tempo',
        sim_mode: 'Modalità',
        sim_speed: 'Velocità',
        sim_mixed: 'Misto',
        
        // Tooltips
        tip_fit: 'Adatta vista',
        tip_delete: 'Elimina selezionato',
        tip_duplicate: 'Duplica selezionato',
        tip_rotate_cw: 'Ruota 90° in senso orario',
        tip_rotate_ccw: 'Ruota 90° in senso antiorario',
        tip_flip_h: 'Specchia in orizzontale',
        tip_flip_v: 'Specchia in verticale',
        tip_gcode: 'Genera G-Code vettoriale',
        tip_simulate: 'Simula incisione laser',
        tip_frame: 'Mostra frame area di lavoro',
        tip_edit_paths: 'Modifica percorsi vettoriali',
        
        // Status
        status_connected: 'Connesso',
        status_disconnected: 'Disconnesso',
        status_ready: 'Pronto',
        
        // Messages
        msg_processing: 'Elaborazione...',
        msg_home_set: 'Home impostata',
        msg_centered: 'Centrato nell\'area di lavoro',
        msg_rotated: 'Ruotato a {deg}°',
        msg_flipped_h: 'Specchiato orizzontalmente',
        msg_flipped_v: 'Specchiato verticalmente',
        msg_select_vector: 'Seleziona un oggetto vettoriale',
        msg_path_deleted: 'Path #{n} eliminato',
        msg_small_paths_deleted: 'Rimossi {n} path piccoli',
        msg_object_deleted: 'Oggetto eliminato',
        msg_duplicated: 'Oggetto duplicato',
        msg_loaded: 'Caricato',
        msg_text_added: 'Testo raster aggiunto',
        msg_vector_text_added: 'Testo vettoriale aggiunto',
        msg_no_chars: 'Nessun carattere supportato nel testo',
        msg_select_image: 'Seleziona un\'immagine per vettorizzare',
        msg_vectorizing: 'Vettorizzazione in corso...',
        msg_no_contours: 'Nessun contorno trovato',
        msg_no_paths_svg: 'Nessun percorso trovato nel file SVG',
        msg_vectorized: '✅ Vettorizzato: {n} contorni',
        msg_no_objects: 'Nessun oggetto nell\'area di lavoro',
        msg_gcode_generated: 'G-Code {mode}: {n} linee generate',
        msg_copied: 'Copiato negli appunti!',
        msg_downloaded: 'File scaricato!',
        msg_nothing_to_simulate: 'Niente da simulare',
        msg_simulation_started: 'Simulazione avviata:',
        msg_simulation_complete: 'Simulazione completata',
        msg_simulation_stopped: 'Simulazione fermata',
        msg_use_chrome: 'Usa Chrome o Edge per la connessione seriale',
        msg_connected: 'Connesso alla macchina',
        msg_disconnected: 'Disconnesso dalla macchina',
        msg_error: 'Errore',
        msg_emergency_stop: '⛔ STOP DI EMERGENZA ATTIVATO',
        msg_not_connected: 'Non connesso alla macchina',
        msg_starting: 'Avvio lavoro...',
        msg_complete: '✅ Lavoro completato con successo',
        msg_paused: 'Lavoro in pausa',
        msg_resumed: 'Lavoro ripreso',
        msg_framing: 'Frame area in corso...',
        msg_profile_saved: 'Profilo macchina salvato',
        msg_preset_applied: 'Preset applicato',
        msg_preset_saved: 'Preset salvato',
        msg_project_saved: 'Progetto salvato',
        msg_project_loaded: 'Progetto caricato',
        
        // Other
        home_tip: '💡 Tasto destro → "Imposta Home qui"',
        edit_mode_label: '✂️ MODALITÀ EDITOR PATH',
        editing: 'Modifica',
        confirm_delete_all: 'Eliminare tutti gli oggetti?'
    },

    // ==========================================
    // ENGLISH
    // ==========================================
    en: {
        _flag: '🇬🇧',
        _name: 'English',
        
        sec_project: '📁 Project',
        sec_machine: '🔧 Machine',
        sec_home: '🏠 Home',
        sec_import: '📁 Import',
        sec_vectorize: '✏️ Vectorization',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Path Editor',
        sec_presets: '🎯 Presets',
        sec_objects: '📦 Objects',
        sec_properties: '⚙️ Properties',
        sec_jog: '🎮 Jog',
        
        btn_save: '💾 Save',
        btn_load: '📂 Load',
        btn_save_profile: '💾 Save Profile',
        btn_set: '📍 Set',
        btn_go: '🏠 Go',
        btn_import_image: '📷 Image/SVG',
        btn_add_text: '📝 Raster Text',
        btn_add_vector_text: '🔤 Vector Text',
        btn_vectorize: '🔄 Vectorize',
        btn_raster_gcode: '📄 Raster G-Code',
        btn_delete: '🗑️ Delete',
        btn_delete_small: '🧹 Small',
        btn_new_preset: '+ New',
        btn_select_all: 'All',
        btn_clear: 'Clear',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Resume',
        btn_exit: '✓ Exit',
        btn_send: 'Send',
        btn_copy: '📋 Copy',
        btn_download: '💾 Download',
        btn_send_machine: '📤 Send',
        btn_create: '✅ Create',
        btn_connect: 'Connect',
        btn_disconnect: 'Disconnect',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_mirror_x: 'Mirror X axis',
        lbl_mirror_y: 'Mirror Y axis',
        lbl_threshold: 'Threshold',
        lbl_border_margin: 'Border margin',
        lbl_remove_borders: 'Remove borders',
        lbl_resolution: 'Resolution',
        lbl_bidirectional: 'Bidirectional',
        lbl_objects: 'Objects',
        lbl_width: 'Width',
        lbl_height: 'Height',
        lbl_lock_ratio: 'Lock ratio',
        lbl_rotation: 'Rotation',
        lbl_power: 'Power',
        lbl_speed: 'Speed',
        lbl_passes: 'Passes',
        lbl_name: 'Name',
        lbl_text: 'Text',
        lbl_size: 'Size (mm)',
        lbl_lines: 'lines',
        lbl_bold: 'Bold',
        
        ctx_set_home_here: '📍 Set Home here',
        ctx_select: '✓ Select',
        ctx_select_all: '☑ Select all',
        ctx_duplicate: '📋 Duplicate',
        ctx_delete: '🗑️ Delete',
        ctx_center: '⊙ Center',
        ctx_rotate_cw: '↻ Rotate 90° clockwise',
        ctx_rotate_ccw: '↺ Rotate 90° counter-clockwise',
        ctx_flip_h: '⇄ Flip horizontal',
        ctx_flip_v: '⇅ Flip vertical',
        ctx_vectorize: '✏️ Vectorize',
        ctx_raster_gcode: '🖼️ Raster G-Code',
        ctx_edit_paths: '✂️ Edit Paths',
        ctx_gcode_vector: '📄 Vector G-Code',
        ctx_simulate: '🎬 Simulate',
        ctx_frame: '🔲 Frame',
        ctx_go_home: '🏠 Go to Home',
        
        modal_new_preset: 'New Preset',
        modal_add_text: 'Add Raster Text',
        modal_add_vector_text: 'Add Vector Text',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vector',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Progress',
        sim_time: 'Time',
        sim_mode: 'Mode',
        sim_speed: 'Speed',
        sim_mixed: 'Mixed',
        
        tip_fit: 'Fit view to work area',
        tip_delete: 'Delete selected object',
        tip_duplicate: 'Duplicate selected object',
        tip_rotate_cw: 'Rotate 90° clockwise',
        tip_rotate_ccw: 'Rotate 90° counter-clockwise',
        tip_flip_h: 'Flip horizontally',
        tip_flip_v: 'Flip vertically',
        tip_gcode: 'Generate vector G-Code',
        tip_simulate: 'Simulate laser engraving',
        tip_frame: 'Show work area frame on machine',
        tip_edit_paths: 'Edit vector paths',
        
        status_connected: 'Connected',
        status_disconnected: 'Disconnected',
        status_ready: 'Ready',
        
        msg_processing: 'Processing...',
        msg_home_set: 'Home position set',
        msg_centered: 'Centered in work area',
        msg_rotated: 'Rotated to {deg}°',
        msg_flipped_h: 'Flipped horizontally',
        msg_flipped_v: 'Flipped vertically',
        msg_select_vector: 'Select a vector object',
        msg_path_deleted: 'Path #{n} deleted',
        msg_small_paths_deleted: 'Removed {n} small paths',
        msg_object_deleted: 'Object deleted',
        msg_duplicated: 'Object duplicated',
        msg_loaded: 'Loaded',
        msg_text_added: 'Raster text added',
        msg_vector_text_added: 'Vector text added',
        msg_no_chars: 'No supported characters in text',
        msg_select_image: 'Select an image to vectorize',
        msg_vectorizing: 'Vectorizing...',
        msg_no_contours: 'No contours found',
        msg_no_paths_svg: 'No paths found in SVG file',
        msg_vectorized: '✅ Vectorized: {n} contours',
        msg_no_objects: 'No objects in work area',
        msg_gcode_generated: 'G-Code {mode}: {n} lines generated',
        msg_copied: 'Copied to clipboard!',
        msg_downloaded: 'File downloaded!',
        msg_nothing_to_simulate: 'Nothing to simulate',
        msg_simulation_started: 'Simulation started:',
        msg_simulation_complete: 'Simulation complete',
        msg_simulation_stopped: 'Simulation stopped',
        msg_use_chrome: 'Use Chrome or Edge for serial connection',
        msg_connected: 'Connected to machine',
        msg_disconnected: 'Disconnected from machine',
        msg_error: 'Error',
        msg_emergency_stop: '⛔ EMERGENCY STOP ACTIVATED',
        msg_not_connected: 'Not connected to machine',
        msg_starting: 'Starting job...',
        msg_complete: '✅ Job completed successfully',
        msg_paused: 'Job paused',
        msg_resumed: 'Job resumed',
        msg_framing: 'Framing work area...',
        msg_profile_saved: 'Machine profile saved',
        msg_preset_applied: 'Preset applied',
        msg_preset_saved: 'Preset saved',
        msg_project_saved: 'Project saved',
        msg_project_loaded: 'Project loaded',
        
        home_tip: '💡 Right-click → "Set Home here"',
        edit_mode_label: '✂️ PATH EDITOR MODE',
        editing: 'Editing',
        confirm_delete_all: 'Delete all objects?'
    },

    // ==========================================
    // FRANÇAIS
    // ==========================================
    fr: {
        _flag: '🇫🇷',
        _name: 'Français',
        
        sec_project: '📁 Projet',
        sec_machine: '🔧 Machine',
        sec_home: '🏠 Origine',
        sec_import: '📁 Importer',
        sec_vectorize: '✏️ Vectorisation',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Éditeur de tracés',
        sec_presets: '🎯 Préréglages',
        sec_objects: '📦 Objets',
        sec_properties: '⚙️ Propriétés',
        sec_jog: '🎮 Déplacement',
        
        btn_save: '💾 Sauver',
        btn_load: '📂 Charger',
        btn_save_profile: '💾 Sauver profil',
        btn_set: '📍 Définir',
        btn_go: '🏠 Aller',
        btn_import_image: '📷 Image/SVG',
        btn_add_text: '📝 Texte raster',
        btn_add_vector_text: '🔤 Texte vectoriel',
        btn_vectorize: '🔄 Vectoriser',
        btn_raster_gcode: '📄 G-Code raster',
        btn_delete: '🗑️ Supprimer',
        btn_delete_small: '🧹 Petits',
        btn_new_preset: '+ Nouveau',
        btn_select_all: 'Tout',
        btn_clear: 'Effacer',
        btn_start: '▶️ DÉMARRER',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Reprendre',
        btn_exit: '✓ Quitter',
        btn_send: 'Envoyer',
        btn_copy: '📋 Copier',
        btn_download: '💾 Télécharger',
        btn_send_machine: '📤 Envoyer',
        btn_create: '✅ Créer',
        btn_connect: 'Connecter',
        btn_disconnect: 'Déconnecter',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_mirror_x: 'Miroir axe X',
        lbl_mirror_y: 'Miroir axe Y',
        lbl_threshold: 'Seuil',
        lbl_border_margin: 'Marge bordure',
        lbl_remove_borders: 'Supprimer bordures',
        lbl_resolution: 'Résolution',
        lbl_bidirectional: 'Bidirectionnel',
        lbl_objects: 'Objets',
        lbl_width: 'Largeur',
        lbl_height: 'Hauteur',
        lbl_lock_ratio: 'Verrouiller proportions',
        lbl_rotation: 'Rotation',
        lbl_power: 'Puissance',
        lbl_speed: 'Vitesse',
        lbl_passes: 'Passes',
        lbl_name: 'Nom',
        lbl_text: 'Texte',
        lbl_size: 'Taille (mm)',
        lbl_lines: 'lignes',
        lbl_bold: 'Gras',
        
        ctx_set_home_here: '📍 Définir l\'origine ici',
        ctx_select: '✓ Sélectionner',
        ctx_select_all: '☑ Tout sélectionner',
        ctx_duplicate: '📋 Dupliquer',
        ctx_delete: '🗑️ Supprimer',
        ctx_center: '⊙ Centrer',
        ctx_rotate_cw: '↻ Rotation 90° sens horaire',
        ctx_rotate_ccw: '↺ Rotation 90° sens antihoraire',
        ctx_flip_h: '⇄ Miroir horizontal',
        ctx_flip_v: '⇅ Miroir vertical',
        ctx_vectorize: '✏️ Vectoriser',
        ctx_raster_gcode: '🖼️ G-Code raster',
        ctx_edit_paths: '✂️ Modifier les tracés',
        ctx_gcode_vector: '📄 G-Code vectoriel',
        ctx_simulate: '🎬 Simuler',
        ctx_frame: '🔲 Cadre',
        ctx_go_home: '🏠 Aller à l\'origine',
        
        modal_new_preset: 'Nouveau préréglage',
        modal_add_text: 'Ajouter texte raster',
        modal_add_vector_text: 'Ajouter texte vectoriel',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vectoriel',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Progression',
        sim_time: 'Temps',
        sim_mode: 'Mode',
        sim_speed: 'Vitesse',
        sim_mixed: 'Mixte',
        
        tip_fit: 'Ajuster la vue à la zone de travail',
        tip_delete: 'Supprimer l\'objet sélectionné',
        tip_duplicate: 'Dupliquer l\'objet sélectionné',
        tip_rotate_cw: 'Rotation 90° sens horaire',
        tip_rotate_ccw: 'Rotation 90° sens antihoraire',
        tip_flip_h: 'Miroir horizontal',
        tip_flip_v: 'Miroir vertical',
        tip_gcode: 'Générer G-Code vectoriel',
        tip_simulate: 'Simuler la gravure laser',
        tip_frame: 'Afficher le cadre de la zone de travail',
        tip_edit_paths: 'Modifier les tracés vectoriels',
        
        status_connected: 'Connecté',
        status_disconnected: 'Déconnecté',
        status_ready: 'Prêt',
        
        msg_processing: 'Traitement en cours...',
        msg_home_set: 'Origine définie',
        msg_centered: 'Centré dans la zone de travail',
        msg_rotated: 'Rotation à {deg}°',
        msg_flipped_h: 'Miroir horizontal appliqué',
        msg_flipped_v: 'Miroir vertical appliqué',
        msg_select_vector: 'Sélectionnez un objet vectoriel',
        msg_path_deleted: 'Tracé #{n} supprimé',
        msg_small_paths_deleted: '{n} petits tracés supprimés',
        msg_object_deleted: 'Objet supprimé',
        msg_duplicated: 'Objet dupliqué',
        msg_loaded: 'Chargé',
        msg_text_added: 'Texte raster ajouté',
        msg_vector_text_added: 'Texte vectoriel ajouté',
        msg_no_chars: 'Aucun caractère supporté dans le texte',
        msg_select_image: 'Sélectionnez une image à vectoriser',
        msg_vectorizing: 'Vectorisation en cours...',
        msg_no_contours: 'Aucun contour trouvé',
        msg_no_paths_svg: 'Aucun tracé trouvé dans le fichier SVG',
        msg_vectorized: '✅ Vectorisé: {n} contours',
        msg_no_objects: 'Aucun objet dans la zone de travail',
        msg_gcode_generated: 'G-Code {mode}: {n} lignes générées',
        msg_copied: 'Copié dans le presse-papiers!',
        msg_downloaded: 'Fichier téléchargé!',
        msg_nothing_to_simulate: 'Rien à simuler',
        msg_simulation_started: 'Simulation démarrée:',
        msg_simulation_complete: 'Simulation terminée',
        msg_simulation_stopped: 'Simulation arrêtée',
        msg_use_chrome: 'Utilisez Chrome ou Edge pour la connexion série',
        msg_connected: 'Connecté à la machine',
        msg_disconnected: 'Déconnecté de la machine',
        msg_error: 'Erreur',
        msg_emergency_stop: '⛔ ARRÊT D\'URGENCE ACTIVÉ',
        msg_not_connected: 'Non connecté à la machine',
        msg_starting: 'Démarrage du travail...',
        msg_complete: '✅ Travail terminé avec succès',
        msg_paused: 'Travail en pause',
        msg_resumed: 'Travail repris',
        msg_framing: 'Cadrage de la zone de travail...',
        msg_profile_saved: 'Profil machine sauvegardé',
        msg_preset_applied: 'Préréglage appliqué',
        msg_preset_saved: 'Préréglage sauvegardé',
        msg_project_saved: 'Projet sauvegardé',
        msg_project_loaded: 'Projet chargé',
        
        home_tip: '💡 Clic droit → "Définir l\'origine ici"',
        edit_mode_label: '✂️ MODE ÉDITEUR DE TRACÉS',
        editing: 'Édition',
        confirm_delete_all: 'Supprimer tous les objets?'
    },

    // ==========================================
    // DEUTSCH
    // ==========================================
    de: {
        _flag: '🇩🇪',
        _name: 'Deutsch',
        
        sec_project: '📁 Projekt',
        sec_machine: '🔧 Maschine',
        sec_home: '🏠 Nullpunkt',
        sec_import: '📁 Importieren',
        sec_vectorize: '✏️ Vektorisierung',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Pfad-Editor',
        sec_presets: '🎯 Voreinstellungen',
        sec_objects: '📦 Objekte',
        sec_properties: '⚙️ Eigenschaften',
        sec_jog: '🎮 Steuerung',
        
        btn_save: '💾 Speichern',
        btn_load: '📂 Laden',
        btn_save_profile: '💾 Profil speichern',
        btn_set: '📍 Setzen',
        btn_go: '🏠 Fahren',
        btn_import_image: '📷 Bild/SVG',
        btn_add_text: '📝 Raster-Text',
        btn_add_vector_text: '🔤 Vektor-Text',
        btn_vectorize: '🔄 Vektorisieren',
        btn_raster_gcode: '📄 Raster-G-Code',
        btn_delete: '🗑️ Löschen',
        btn_delete_small: '🧹 Kleine',
        btn_new_preset: '+ Neu',
        btn_select_all: 'Alle',
        btn_clear: 'Leeren',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Fortsetzen',
        btn_exit: '✓ Beenden',
        btn_send: 'Senden',
        btn_copy: '📋 Kopieren',
        btn_download: '💾 Herunterladen',
        btn_send_machine: '📤 Senden',
        btn_create: '✅ Erstellen',
        btn_connect: 'Verbinden',
        btn_disconnect: 'Trennen',
        btn_stop: 'STOPP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_mirror_x: 'X-Achse spiegeln',
        lbl_mirror_y: 'Y-Achse spiegeln',
        lbl_threshold: 'Schwellenwert',
        lbl_border_margin: 'Randabstand',
        lbl_remove_borders: 'Ränder entfernen',
        lbl_resolution: 'Auflösung',
        lbl_bidirectional: 'Bidirektional',
        lbl_objects: 'Objekte',
        lbl_width: 'Breite',
        lbl_height: 'Höhe',
        lbl_lock_ratio: 'Seitenverhältnis sperren',
        lbl_rotation: 'Drehung',
        lbl_power: 'Leistung',
        lbl_speed: 'Geschwindigkeit',
        lbl_passes: 'Durchgänge',
        lbl_name: 'Name',
        lbl_text: 'Text',
        lbl_size: 'Größe (mm)',
        lbl_lines: 'Zeilen',
        lbl_bold: 'Fett',
        
        ctx_set_home_here: '📍 Nullpunkt hier setzen',
        ctx_select: '✓ Auswählen',
        ctx_select_all: '☑ Alles auswählen',
        ctx_duplicate: '📋 Duplizieren',
        ctx_delete: '🗑️ Löschen',
        ctx_center: '⊙ Zentrieren',
        ctx_rotate_cw: '↻ 90° im Uhrzeigersinn drehen',
        ctx_rotate_ccw: '↺ 90° gegen den Uhrzeigersinn drehen',
        ctx_flip_h: '⇄ Horizontal spiegeln',
        ctx_flip_v: '⇅ Vertikal spiegeln',
        ctx_vectorize: '✏️ Vektorisieren',
        ctx_raster_gcode: '🖼️ Raster-G-Code',
        ctx_edit_paths: '✂️ Pfade bearbeiten',
        ctx_gcode_vector: '📄 Vektor-G-Code',
        ctx_simulate: '🎬 Simulieren',
        ctx_frame: '🔲 Rahmen',
        ctx_go_home: '🏠 Zum Nullpunkt fahren',
        
        modal_new_preset: 'Neue Voreinstellung',
        modal_add_text: 'Raster-Text hinzufügen',
        modal_add_vector_text: 'Vektor-Text hinzufügen',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vektor',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Fortschritt',
        sim_time: 'Zeit',
        sim_mode: 'Modus',
        sim_speed: 'Geschwindigkeit',
        sim_mixed: 'Gemischt',
        
        tip_fit: 'Ansicht an Arbeitsbereich anpassen',
        tip_delete: 'Ausgewähltes Objekt löschen',
        tip_duplicate: 'Ausgewähltes Objekt duplizieren',
        tip_rotate_cw: '90° im Uhrzeigersinn drehen',
        tip_rotate_ccw: '90° gegen den Uhrzeigersinn drehen',
        tip_flip_h: 'Horizontal spiegeln',
        tip_flip_v: 'Vertikal spiegeln',
        tip_gcode: 'Vektor-G-Code generieren',
        tip_simulate: 'Lasergravur simulieren',
        tip_frame: 'Arbeitsbereich-Rahmen auf Maschine anzeigen',
        tip_edit_paths: 'Vektorpfade bearbeiten',
        
        status_connected: 'Verbunden',
        status_disconnected: 'Getrennt',
        status_ready: 'Bereit',
        
        msg_processing: 'Verarbeitung...',
        msg_home_set: 'Nullpunkt gesetzt',
        msg_centered: 'Im Arbeitsbereich zentriert',
        msg_rotated: 'Auf {deg}° gedreht',
        msg_flipped_h: 'Horizontal gespiegelt',
        msg_flipped_v: 'Vertikal gespiegelt',
        msg_select_vector: 'Wählen Sie ein Vektorobjekt',
        msg_path_deleted: 'Pfad #{n} gelöscht',
        msg_small_paths_deleted: '{n} kleine Pfade entfernt',
        msg_object_deleted: 'Objekt gelöscht',
        msg_duplicated: 'Objekt dupliziert',
        msg_loaded: 'Geladen',
        msg_text_added: 'Raster-Text hinzugefügt',
        msg_vector_text_added: 'Vektor-Text hinzugefügt',
        msg_no_chars: 'Keine unterstützten Zeichen im Text',
        msg_select_image: 'Wählen Sie ein Bild zum Vektorisieren',
        msg_vectorizing: 'Vektorisierung läuft...',
        msg_no_contours: 'Keine Konturen gefunden',
        msg_no_paths_svg: 'Keine Pfade in der SVG-Datei gefunden',
        msg_vectorized: '✅ Vektorisiert: {n} Konturen',
        msg_no_objects: 'Keine Objekte im Arbeitsbereich',
        msg_gcode_generated: 'G-Code {mode}: {n} Zeilen generiert',
        msg_copied: 'In die Zwischenablage kopiert!',
        msg_downloaded: 'Datei heruntergeladen!',
        msg_nothing_to_simulate: 'Nichts zu simulieren',
        msg_simulation_started: 'Simulation gestartet:',
        msg_simulation_complete: 'Simulation abgeschlossen',
        msg_simulation_stopped: 'Simulation gestoppt',
        msg_use_chrome: 'Verwenden Sie Chrome oder Edge für die serielle Verbindung',
        msg_connected: 'Mit Maschine verbunden',
        msg_disconnected: 'Von Maschine getrennt',
        msg_error: 'Fehler',
        msg_emergency_stop: '⛔ NOT-HALT AKTIVIERT',
        msg_not_connected: 'Nicht mit Maschine verbunden',
        msg_starting: 'Auftrag wird gestartet...',
        msg_complete: '✅ Auftrag erfolgreich abgeschlossen',
        msg_paused: 'Auftrag pausiert',
        msg_resumed: 'Auftrag fortgesetzt',
        msg_framing: 'Arbeitsbereich wird umrahmt...',
        msg_profile_saved: 'Maschinenprofil gespeichert',
        msg_preset_applied: 'Voreinstellung angewendet',
        msg_preset_saved: 'Voreinstellung gespeichert',
        msg_project_saved: 'Projekt gespeichert',
        msg_project_loaded: 'Projekt geladen',
        
        home_tip: '💡 Rechtsklick → "Nullpunkt hier setzen"',
        edit_mode_label: '✂️ PFAD-EDITOR-MODUS',
        editing: 'Bearbeitung',
        confirm_delete_all: 'Alle Objekte löschen?'
    },
        // ==========================================
    // ESPAÑOL
    // ==========================================
    es: {
        _flag: '🇪🇸',
        _name: 'Español',
        
        sec_project: '📁 Proyecto',
        sec_machine: '🔧 Máquina',
        sec_home: '🏠 Origen',
        sec_import: '📁 Importar',
        sec_vectorize: '✏️ Vectorización',
        sec_raster: '🖼️ Ráster',
        sec_path_editor: '✂️ Editor de trazados',
        sec_presets: '🎯 Preajustes',
        sec_objects: '📦 Objetos',
        sec_properties: '⚙️ Propiedades',
        sec_jog: '🎮 Control',
        
        btn_save: '💾 Guardar',
        btn_load: '📂 Cargar',
        btn_save_profile: '💾 Guardar perfil',
        btn_set: '📍 Establecer',
        btn_go: '🏠 Ir',
        btn_import_image: '📷 Imagen/SVG',
        btn_add_text: '📝 Texto ráster',
        btn_add_vector_text: '🔤 Texto vectorial',
        btn_vectorize: '🔄 Vectorizar',
        btn_raster_gcode: '📄 G-Code ráster',
        btn_delete: '🗑️ Eliminar',
        btn_delete_small: '🧹 Pequeños',
        btn_new_preset: '+ Nuevo',
        btn_select_all: 'Todos',
        btn_clear: 'Limpiar',
        btn_start: '▶️ INICIAR',
        btn_pause: '⏸️ Pausar',
        btn_resume: '▶️ Reanudar',
        btn_exit: '✓ Salir',
        btn_send: 'Enviar',
        btn_copy: '📋 Copiar',
        btn_download: '💾 Descargar',
        btn_send_machine: '📤 Enviar',
        btn_create: '✅ Crear',
        btn_connect: 'Conectar',
        btn_disconnect: 'Desconectar',
        btn_stop: 'PARAR ⛔',
        
        lbl_x_max: 'X Máx',
        lbl_y_max: 'Y Máx',
        lbl_mirror_x: 'Espejo eje X',
        lbl_mirror_y: 'Espejo eje Y',
        lbl_threshold: 'Umbral',
        lbl_border_margin: 'Margen del borde',
        lbl_remove_borders: 'Eliminar bordes',
        lbl_resolution: 'Resolución',
        lbl_bidirectional: 'Bidireccional',
        lbl_objects: 'Objetos',
        lbl_width: 'Ancho',
        lbl_height: 'Alto',
        lbl_lock_ratio: 'Bloquear proporción',
        lbl_rotation: 'Rotación',
        lbl_power: 'Potencia',
        lbl_speed: 'Velocidad',
        lbl_passes: 'Pasadas',
        lbl_name: 'Nombre',
        lbl_text: 'Texto',
        lbl_size: 'Tamaño (mm)',
        lbl_lines: 'líneas',
        lbl_bold: 'Negrita',
        
        ctx_set_home_here: '📍 Establecer origen aquí',
        ctx_select: '✓ Seleccionar',
        ctx_select_all: '☑ Seleccionar todo',
        ctx_duplicate: '📋 Duplicar',
        ctx_delete: '🗑️ Eliminar',
        ctx_center: '⊙ Centrar',
        ctx_rotate_cw: '↻ Rotar 90° horario',
        ctx_rotate_ccw: '↺ Rotar 90° antihorario',
        ctx_flip_h: '⇄ Voltear horizontal',
        ctx_flip_v: '⇅ Voltear vertical',
        ctx_vectorize: '✏️ Vectorizar',
        ctx_raster_gcode: '🖼️ G-Code ráster',
        ctx_edit_paths: '✂️ Editar trazados',
        ctx_gcode_vector: '📄 G-Code vectorial',
        ctx_simulate: '🎬 Simular',
        ctx_frame: '🔲 Marco',
        ctx_go_home: '🏠 Ir al origen',
        
        modal_new_preset: 'Nuevo preajuste',
        modal_add_text: 'Añadir texto ráster',
        modal_add_vector_text: 'Añadir texto vectorial',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vectorial',
        tab_raster: 'Ráster',
        
        sim_title: '🎬 Simulación',
        sim_pos: 'Pos',
        sim_progress: 'Progreso',
        sim_time: 'Tiempo',
        sim_mode: 'Modo',
        sim_speed: 'Velocidad',
        sim_mixed: 'Mixto',
        
        tip_fit: 'Ajustar vista al área de trabajo',
        tip_delete: 'Eliminar objeto seleccionado',
        tip_duplicate: 'Duplicar objeto seleccionado',
        tip_rotate_cw: 'Rotar 90° en sentido horario',
        tip_rotate_ccw: 'Rotar 90° en sentido antihorario',
        tip_flip_h: 'Voltear horizontalmente',
        tip_flip_v: 'Voltear verticalmente',
        tip_gcode: 'Generar G-Code vectorial',
        tip_simulate: 'Simular grabado láser',
        tip_frame: 'Mostrar marco del área de trabajo',
        tip_edit_paths: 'Editar trazados vectoriales',
        
        status_connected: 'Conectado',
        status_disconnected: 'Desconectado',
        status_ready: 'Listo',
        
        msg_processing: 'Procesando...',
        msg_home_set: 'Origen establecido',
        msg_centered: 'Centrado en el área de trabajo',
        msg_rotated: 'Rotado a {deg}°',
        msg_flipped_h: 'Volteado horizontalmente',
        msg_flipped_v: 'Volteado verticalmente',
        msg_select_vector: 'Seleccione un objeto vectorial',
        msg_path_deleted: 'Trazado #{n} eliminado',
        msg_small_paths_deleted: '{n} trazados pequeños eliminados',
        msg_object_deleted: 'Objeto eliminado',
        msg_duplicated: 'Objeto duplicado',
        msg_loaded: 'Cargado',
        msg_text_added: 'Texto ráster añadido',
        msg_vector_text_added: 'Texto vectorial añadido',
        msg_no_chars: 'No hay caracteres soportados en el texto',
        msg_select_image: 'Seleccione una imagen para vectorizar',
        msg_vectorizing: 'Vectorizando...',
        msg_no_contours: 'No se encontraron contornos',
        msg_no_paths_svg: 'No se encontraron trazados en el archivo SVG',
        msg_vectorized: '✅ Vectorizado: {n} contornos',
        msg_no_objects: 'No hay objetos en el área de trabajo',
        msg_gcode_generated: 'G-Code {mode}: {n} líneas generadas',
        msg_copied: '¡Copiado al portapapeles!',
        msg_downloaded: '¡Archivo descargado!',
        msg_nothing_to_simulate: 'Nada que simular',
        msg_simulation_started: 'Simulación iniciada:',
        msg_simulation_complete: 'Simulación completada',
        msg_simulation_stopped: 'Simulación detenida',
        msg_use_chrome: 'Use Chrome o Edge para conexión serie',
        msg_connected: 'Conectado a la máquina',
        msg_disconnected: 'Desconectado de la máquina',
        msg_error: 'Error',
        msg_emergency_stop: '⛔ PARADA DE EMERGENCIA ACTIVADA',
        msg_not_connected: 'No conectado a la máquina',
        msg_starting: 'Iniciando trabajo...',
        msg_complete: '✅ Trabajo completado con éxito',
        msg_paused: 'Trabajo en pausa',
        msg_resumed: 'Trabajo reanudado',
        msg_framing: 'Enmarcando área de trabajo...',
        msg_profile_saved: 'Perfil de máquina guardado',
        msg_preset_applied: 'Preajuste aplicado',
        msg_preset_saved: 'Preajuste guardado',
        msg_project_saved: 'Proyecto guardado',
        msg_project_loaded: 'Proyecto cargado',
        
        home_tip: '💡 Clic derecho → "Establecer origen aquí"',
        edit_mode_label: '✂️ MODO EDITOR DE TRAZADOS',
        editing: 'Editando',
        confirm_delete_all: '¿Eliminar todos los objetos?'
    },

    // ==========================================
    // PORTUGUÊS
    // ==========================================
    pt: {
        _flag: '🇵🇹',
        _name: 'Português',
        
        sec_project: '📁 Projeto',
        sec_machine: '🔧 Máquina',
        sec_home: '🏠 Origem',
        sec_import: '📁 Importar',
        sec_vectorize: '✏️ Vetorização',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Editor de caminhos',
        sec_presets: '🎯 Predefinições',
        sec_objects: '📦 Objetos',
        sec_properties: '⚙️ Propriedades',
        sec_jog: '🎮 Controlo',
        
        btn_save: '💾 Guardar',
        btn_load: '📂 Carregar',
        btn_save_profile: '💾 Guardar perfil',
        btn_set: '📍 Definir',
        btn_go: '🏠 Ir',
        btn_import_image: '📷 Imagem/SVG',
        btn_add_text: '📝 Texto raster',
        btn_add_vector_text: '🔤 Texto vetorial',
        btn_vectorize: '🔄 Vetorizar',
        btn_raster_gcode: '📄 G-Code raster',
        btn_delete: '🗑️ Eliminar',
        btn_delete_small: '🧹 Pequenos',
        btn_new_preset: '+ Novo',
        btn_select_all: 'Todos',
        btn_clear: 'Limpar',
        btn_start: '▶️ INICIAR',
        btn_pause: '⏸️ Pausar',
        btn_resume: '▶️ Retomar',
        btn_exit: '✓ Sair',
        btn_send: 'Enviar',
        btn_copy: '📋 Copiar',
        btn_download: '💾 Transferir',
        btn_send_machine: '📤 Enviar',
        btn_create: '✅ Criar',
        btn_connect: 'Ligar',
        btn_disconnect: 'Desligar',
        btn_stop: 'PARAR ⛔',
        
        lbl_x_max: 'X Máx',
        lbl_y_max: 'Y Máx',
        lbl_mirror_x: 'Espelhar eixo X',
        lbl_mirror_y: 'Espelhar eixo Y',
        lbl_threshold: 'Limiar',
        lbl_border_margin: 'Margem da borda',
        lbl_remove_borders: 'Remover bordas',
        lbl_resolution: 'Resolução',
        lbl_bidirectional: 'Bidirecional',
        lbl_objects: 'Objetos',
        lbl_width: 'Largura',
        lbl_height: 'Altura',
        lbl_lock_ratio: 'Bloquear proporção',
        lbl_rotation: 'Rotação',
        lbl_power: 'Potência',
        lbl_speed: 'Velocidade',
        lbl_passes: 'Passagens',
        lbl_name: 'Nome',
        lbl_text: 'Texto',
        lbl_size: 'Tamanho (mm)',
        lbl_lines: 'linhas',
        lbl_bold: 'Negrito',
        
        ctx_set_home_here: '📍 Definir origem aqui',
        ctx_select: '✓ Selecionar',
        ctx_select_all: '☑ Selecionar tudo',
        ctx_duplicate: '📋 Duplicar',
        ctx_delete: '🗑️ Eliminar',
        ctx_center: '⊙ Centrar',
        ctx_rotate_cw: '↻ Rodar 90° horário',
        ctx_rotate_ccw: '↺ Rodar 90° anti-horário',
        ctx_flip_h: '⇄ Espelhar horizontal',
        ctx_flip_v: '⇅ Espelhar vertical',
        ctx_vectorize: '✏️ Vetorizar',
        ctx_raster_gcode: '🖼️ G-Code raster',
        ctx_edit_paths: '✂️ Editar caminhos',
        ctx_gcode_vector: '📄 G-Code vetorial',
        ctx_simulate: '🎬 Simular',
        ctx_frame: '🔲 Moldura',
        ctx_go_home: '🏠 Ir para origem',
        
        modal_new_preset: 'Nova predefinição',
        modal_add_text: 'Adicionar texto raster',
        modal_add_vector_text: 'Adicionar texto vetorial',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vetorial',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulação',
        sim_pos: 'Pos',
        sim_progress: 'Progresso',
        sim_time: 'Tempo',
        sim_mode: 'Modo',
        sim_speed: 'Velocidade',
        sim_mixed: 'Misto',
        
        tip_fit: 'Ajustar vista à área de trabalho',
        tip_delete: 'Eliminar objeto selecionado',
        tip_duplicate: 'Duplicar objeto selecionado',
        tip_rotate_cw: 'Rodar 90° no sentido horário',
        tip_rotate_ccw: 'Rodar 90° no sentido anti-horário',
        tip_flip_h: 'Espelhar horizontalmente',
        tip_flip_v: 'Espelhar verticalmente',
        tip_gcode: 'Gerar G-Code vetorial',
        tip_simulate: 'Simular gravação a laser',
        tip_frame: 'Mostrar moldura da área de trabalho',
        tip_edit_paths: 'Editar caminhos vetoriais',
        
        status_connected: 'Ligado',
        status_disconnected: 'Desligado',
        status_ready: 'Pronto',
        
        msg_processing: 'A processar...',
        msg_home_set: 'Origem definida',
        msg_centered: 'Centrado na área de trabalho',
        msg_rotated: 'Rodado para {deg}°',
        msg_flipped_h: 'Espelhado horizontalmente',
        msg_flipped_v: 'Espelhado verticalmente',
        msg_select_vector: 'Selecione um objeto vetorial',
        msg_path_deleted: 'Caminho #{n} eliminado',
        msg_small_paths_deleted: '{n} caminhos pequenos eliminados',
        msg_object_deleted: 'Objeto eliminado',
        msg_duplicated: 'Objeto duplicado',
        msg_loaded: 'Carregado',
        msg_text_added: 'Texto raster adicionado',
        msg_vector_text_added: 'Texto vetorial adicionado',
        msg_no_chars: 'Sem caracteres suportados no texto',
        msg_select_image: 'Selecione uma imagem para vetorizar',
        msg_vectorizing: 'A vetorizar...',
        msg_no_contours: 'Nenhum contorno encontrado',
        msg_no_paths_svg: 'Nenhum caminho encontrado no ficheiro SVG',
        msg_vectorized: '✅ Vetorizado: {n} contornos',
        msg_no_objects: 'Sem objetos na área de trabalho',
        msg_gcode_generated: 'G-Code {mode}: {n} linhas geradas',
        msg_copied: 'Copiado para a área de transferência!',
        msg_downloaded: 'Ficheiro transferido!',
        msg_nothing_to_simulate: 'Nada para simular',
        msg_simulation_started: 'Simulação iniciada:',
        msg_simulation_complete: 'Simulação concluída',
        msg_simulation_stopped: 'Simulação parada',
        msg_use_chrome: 'Use Chrome ou Edge para ligação série',
        msg_connected: 'Ligado à máquina',
        msg_disconnected: 'Desligado da máquina',
        msg_error: 'Erro',
        msg_emergency_stop: '⛔ PARAGEM DE EMERGÊNCIA ATIVADA',
        msg_not_connected: 'Não ligado à máquina',
        msg_starting: 'A iniciar trabalho...',
        msg_complete: '✅ Trabalho concluído com sucesso',
        msg_paused: 'Trabalho em pausa',
        msg_resumed: 'Trabalho retomado',
        msg_framing: 'A enquadrar área de trabalho...',
        msg_profile_saved: 'Perfil de máquina guardado',
        msg_preset_applied: 'Predefinição aplicada',
        msg_preset_saved: 'Predefinição guardada',
        msg_project_saved: 'Projeto guardado',
        msg_project_loaded: 'Projeto carregado',
        
        home_tip: '💡 Clique direito → "Definir origem aqui"',
        edit_mode_label: '✂️ MODO EDITOR DE CAMINHOS',
        editing: 'A editar',
        confirm_delete_all: 'Eliminar todos os objetos?'
    },

    // ==========================================
    // NEDERLANDS
    // ==========================================
    nl: {
        _flag: '🇳🇱',
        _name: 'Nederlands',
        
        sec_project: '📁 Project',
        sec_machine: '🔧 Machine',
        sec_home: '🏠 Thuispositie',
        sec_import: '📁 Importeren',
        sec_vectorize: '✏️ Vectorisatie',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Pad-editor',
        sec_presets: '🎯 Voorinstellingen',
        sec_objects: '📦 Objecten',
        sec_properties: '⚙️ Eigenschappen',
        sec_jog: '🎮 Besturing',
        
        btn_save: '💾 Opslaan',
        btn_load: '📂 Laden',
        btn_save_profile: '💾 Profiel opslaan',
        btn_set: '📍 Instellen',
        btn_go: '🏠 Ga',
        btn_import_image: '📷 Afbeelding/SVG',
        btn_add_text: '📝 Rastertekst',
        btn_add_vector_text: '🔤 Vectortekst',
        btn_vectorize: '🔄 Vectoriseren',
        btn_raster_gcode: '📄 Raster G-Code',
        btn_delete: '🗑️ Verwijderen',
        btn_delete_small: '🧹 Kleine',
        btn_new_preset: '+ Nieuw',
        btn_select_all: 'Alle',
        btn_clear: 'Wissen',
        btn_start: '▶️ STARTEN',
        btn_pause: '⏸️ Pauze',
        btn_resume: '▶️ Hervatten',
        btn_exit: '✓ Afsluiten',
        btn_send: 'Verzenden',
        btn_copy: '📋 Kopiëren',
        btn_download: '💾 Downloaden',
        btn_send_machine: '📤 Verzenden',
        btn_create: '✅ Maken',
        btn_connect: 'Verbinden',
        btn_disconnect: 'Verbreken',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_mirror_x: 'Spiegel X-as',
        lbl_mirror_y: 'Spiegel Y-as',
        lbl_threshold: 'Drempel',
        lbl_border_margin: 'Randmarge',
        lbl_remove_borders: 'Randen verwijderen',
        lbl_resolution: 'Resolutie',
        lbl_bidirectional: 'Bidirectioneel',
        lbl_objects: 'Objecten',
        lbl_width: 'Breedte',
        lbl_height: 'Hoogte',
        lbl_lock_ratio: 'Verhouding vergrendelen',
        lbl_rotation: 'Rotatie',
        lbl_power: 'Vermogen',
        lbl_speed: 'Snelheid',
        lbl_passes: 'Passages',
        lbl_name: 'Naam',
        lbl_text: 'Tekst',
        lbl_size: 'Grootte (mm)',
        lbl_lines: 'regels',
        lbl_bold: 'Vet',
        
        ctx_set_home_here: '📍 Thuispositie hier instellen',
        ctx_select: '✓ Selecteren',
        ctx_select_all: '☑ Alles selecteren',
        ctx_duplicate: '📋 Dupliceren',
        ctx_delete: '🗑️ Verwijderen',
        ctx_center: '⊙ Centreren',
        ctx_rotate_cw: '↻ 90° rechtsom draaien',
        ctx_rotate_ccw: '↺ 90° linksom draaien',
        ctx_flip_h: '⇄ Horizontaal spiegelen',
        ctx_flip_v: '⇅ Verticaal spiegelen',
        ctx_vectorize: '✏️ Vectoriseren',
        ctx_raster_gcode: '🖼️ Raster G-Code',
        ctx_edit_paths: '✂️ Paden bewerken',
        ctx_gcode_vector: '📄 Vector G-Code',
        ctx_simulate: '🎬 Simuleren',
        ctx_frame: '🔲 Kader',
        ctx_go_home: '🏠 Naar thuispositie',
        
        modal_new_preset: 'Nieuwe voorinstelling',
        modal_add_text: 'Rastertekst toevoegen',
        modal_add_vector_text: 'Vectortekst toevoegen',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vector',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulatie',
        sim_pos: 'Pos',
        sim_progress: 'Voortgang',
        sim_time: 'Tijd',
        sim_mode: 'Modus',
        sim_speed: 'Snelheid',
        sim_mixed: 'Gemengd',
        
        tip_fit: 'Weergave aanpassen aan werkgebied',
        tip_delete: 'Geselecteerd object verwijderen',
        tip_duplicate: 'Geselecteerd object dupliceren',
        tip_rotate_cw: '90° rechtsom draaien',
        tip_rotate_ccw: '90° linksom draaien',
        tip_flip_h: 'Horizontaal spiegelen',
        tip_flip_v: 'Verticaal spiegelen',
        tip_gcode: 'Vector G-Code genereren',
        tip_simulate: 'Lasergravure simuleren',
        tip_frame: 'Werkgebied kader tonen',
        tip_edit_paths: 'Vectorpaden bewerken',
        
        status_connected: 'Verbonden',
        status_disconnected: 'Verbroken',
        status_ready: 'Gereed',
        
        msg_processing: 'Verwerken...',
        msg_home_set: 'Thuispositie ingesteld',
        msg_centered: 'Gecentreerd in werkgebied',
        msg_rotated: 'Gedraaid naar {deg}°',
        msg_flipped_h: 'Horizontaal gespiegeld',
        msg_flipped_v: 'Verticaal gespiegeld',
        msg_select_vector: 'Selecteer een vectorobject',
        msg_path_deleted: 'Pad #{n} verwijderd',
        msg_small_paths_deleted: '{n} kleine paden verwijderd',
        msg_object_deleted: 'Object verwijderd',
        msg_duplicated: 'Object gedupliceerd',
        msg_loaded: 'Geladen',
        msg_text_added: 'Rastertekst toegevoegd',
        msg_vector_text_added: 'Vectortekst toegevoegd',
        msg_no_chars: 'Geen ondersteunde tekens in tekst',
        msg_select_image: 'Selecteer een afbeelding om te vectoriseren',
        msg_vectorizing: 'Vectoriseren...',
        msg_no_contours: 'Geen contouren gevonden',
        msg_no_paths_svg: 'Geen paden gevonden in SVG-bestand',
        msg_vectorized: '✅ Gevectoriseerd: {n} contouren',
        msg_no_objects: 'Geen objecten in werkgebied',
        msg_gcode_generated: 'G-Code {mode}: {n} regels gegenereerd',
        msg_copied: 'Gekopieerd naar klembord!',
        msg_downloaded: 'Bestand gedownload!',
        msg_nothing_to_simulate: 'Niets om te simuleren',
        msg_simulation_started: 'Simulatie gestart:',
        msg_simulation_complete: 'Simulatie voltooid',
        msg_simulation_stopped: 'Simulatie gestopt',
        msg_use_chrome: 'Gebruik Chrome of Edge voor seriële verbinding',
        msg_connected: 'Verbonden met machine',
        msg_disconnected: 'Verbinding met machine verbroken',
        msg_error: 'Fout',
        msg_emergency_stop: '⛔ NOODSTOP GEACTIVEERD',
        msg_not_connected: 'Niet verbonden met machine',
        msg_starting: 'Taak starten...',
        msg_complete: '✅ Taak succesvol voltooid',
        msg_paused: 'Taak gepauzeerd',
        msg_resumed: 'Taak hervat',
        msg_framing: 'Werkgebied kadert...',
        msg_profile_saved: 'Machineprofiel opgeslagen',
        msg_preset_applied: 'Voorinstelling toegepast',
        msg_preset_saved: 'Voorinstelling opgeslagen',
        msg_project_saved: 'Project opgeslagen',
        msg_project_loaded: 'Project geladen',
        
        home_tip: '💡 Rechtsklik → "Thuispositie hier instellen"',
        edit_mode_label: '✂️ PAD-EDITOR MODUS',
        editing: 'Bewerken',
        confirm_delete_all: 'Alle objecten verwijderen?'
    },

    // ==========================================
    // POLSKI
    // ==========================================
    pl: {
        _flag: '🇵🇱',
        _name: 'Polski',
        
        sec_project: '📁 Projekt',
        sec_machine: '🔧 Maszyna',
        sec_home: '🏠 Pozycja zerowa',
        sec_import: '📁 Importuj',
        sec_vectorize: '✏️ Wektoryzacja',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Edytor ścieżek',
        sec_presets: '🎯 Ustawienia',
        sec_objects: '📦 Obiekty',
        sec_properties: '⚙️ Właściwości',
        sec_jog: '🎮 Sterowanie',
        
        btn_save: '💾 Zapisz',
        btn_load: '📂 Wczytaj',
        btn_save_profile: '💾 Zapisz profil',
        btn_set: '📍 Ustaw',
        btn_go: '🏠 Idź',
        btn_import_image: '📷 Obraz/SVG',
        btn_add_text: '📝 Tekst rastrowy',
        btn_add_vector_text: '🔤 Tekst wektorowy',
        btn_vectorize: '🔄 Wektoryzuj',
        btn_raster_gcode: '📄 G-Code rastrowy',
        btn_delete: '🗑️ Usuń',
        btn_delete_small: '🧹 Małe',
        btn_new_preset: '+ Nowe',
        btn_select_all: 'Wszystkie',
        btn_clear: 'Wyczyść',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pauza',
        btn_resume: '▶️ Wznów',
        btn_exit: '✓ Wyjdź',
        btn_send: 'Wyślij',
        btn_copy: '📋 Kopiuj',
        btn_download: '💾 Pobierz',
        btn_send_machine: '📤 Wyślij',
        btn_create: '✅ Utwórz',
        btn_connect: 'Połącz',
        btn_disconnect: 'Rozłącz',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Maks',
        lbl_y_max: 'Y Maks',
        lbl_mirror_x: 'Odbij oś X',
        lbl_mirror_y: 'Odbij oś Y',
        lbl_threshold: 'Próg',
        lbl_border_margin: 'Margines krawędzi',
        lbl_remove_borders: 'Usuń krawędzie',
        lbl_resolution: 'Rozdzielczość',
        lbl_bidirectional: 'Dwukierunkowy',
        lbl_objects: 'Obiekty',
        lbl_width: 'Szerokość',
        lbl_height: 'Wysokość',
        lbl_lock_ratio: 'Zablokuj proporcje',
        lbl_rotation: 'Obrót',
        lbl_power: 'Moc',
        lbl_speed: 'Prędkość',
        lbl_passes: 'Przejścia',
        lbl_name: 'Nazwa',
        lbl_text: 'Tekst',
        lbl_size: 'Rozmiar (mm)',
        lbl_lines: 'linie',
        lbl_bold: 'Pogrubienie',
        
        ctx_set_home_here: '📍 Ustaw pozycję zerową tutaj',
        ctx_select: '✓ Wybierz',
        ctx_select_all: '☑ Zaznacz wszystko',
        ctx_duplicate: '📋 Duplikuj',
        ctx_delete: '🗑️ Usuń',
        ctx_center: '⊙ Wyśrodkuj',
        ctx_rotate_cw: '↻ Obróć 90° zgodnie z ruchem wskazówek',
        ctx_rotate_ccw: '↺ Obróć 90° przeciwnie do ruchu wskazówek',
        ctx_flip_h: '⇄ Odbij poziomo',
        ctx_flip_v: '⇅ Odbij pionowo',
        ctx_vectorize: '✏️ Wektoryzuj',
        ctx_raster_gcode: '🖼️ G-Code rastrowy',
        ctx_edit_paths: '✂️ Edytuj ścieżki',
        ctx_gcode_vector: '📄 G-Code wektorowy',
        ctx_simulate: '🎬 Symuluj',
        ctx_frame: '🔲 Ramka',
        ctx_go_home: '🏠 Idź do pozycji zerowej',
        
        modal_new_preset: 'Nowe ustawienie',
        modal_add_text: 'Dodaj tekst rastrowy',
        modal_add_vector_text: 'Dodaj tekst wektorowy',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Wektor',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Symulacja',
        sim_pos: 'Poz',
        sim_progress: 'Postęp',
        sim_time: 'Czas',
        sim_mode: 'Tryb',
        sim_speed: 'Prędkość',
        sim_mixed: 'Mieszany',
        
        tip_fit: 'Dopasuj widok do obszaru roboczego',
        tip_delete: 'Usuń wybrany obiekt',
        tip_duplicate: 'Duplikuj wybrany obiekt',
        tip_rotate_cw: 'Obróć 90° zgodnie z ruchem wskazówek',
        tip_rotate_ccw: 'Obróć 90° przeciwnie do ruchu wskazówek',
        tip_flip_h: 'Odbij poziomo',
        tip_flip_v: 'Odbij pionowo',
        tip_gcode: 'Generuj wektorowy G-Code',
        tip_simulate: 'Symuluj grawerowanie laserowe',
        tip_frame: 'Pokaż ramkę obszaru roboczego',
        tip_edit_paths: 'Edytuj ścieżki wektorowe',
        
        status_connected: 'Połączono',
        status_disconnected: 'Rozłączono',
        status_ready: 'Gotowy',
        
        msg_processing: 'Przetwarzanie...',
        msg_home_set: 'Pozycja zerowa ustawiona',
        msg_centered: 'Wyśrodkowano w obszarze roboczym',
        msg_rotated: 'Obrócono do {deg}°',
        msg_flipped_h: 'Odbito poziomo',
        msg_flipped_v: 'Odbito pionowo',
        msg_select_vector: 'Wybierz obiekt wektorowy',
        msg_path_deleted: 'Ścieżka #{n} usunięta',
        msg_small_paths_deleted: 'Usunięto {n} małych ścieżek',
        msg_object_deleted: 'Obiekt usunięty',
        msg_duplicated: 'Obiekt zduplikowany',
        msg_loaded: 'Wczytano',
        msg_text_added: 'Dodano tekst rastrowy',
        msg_vector_text_added: 'Dodano tekst wektorowy',
        msg_no_chars: 'Brak obsługiwanych znaków w tekście',
        msg_select_image: 'Wybierz obraz do wektoryzacji',
        msg_vectorizing: 'Wektoryzacja...',
        msg_no_contours: 'Nie znaleziono konturów',
        msg_no_paths_svg: 'Nie znaleziono ścieżek w pliku SVG',
        msg_vectorized: '✅ Zwektoryzowano: {n} konturów',
        msg_no_objects: 'Brak obiektów w obszarze roboczym',
        msg_gcode_generated: 'G-Code {mode}: wygenerowano {n} linii',
        msg_copied: 'Skopiowano do schowka!',
        msg_downloaded: 'Plik pobrany!',
        msg_nothing_to_simulate: 'Nic do symulacji',
        msg_simulation_started: 'Symulacja rozpoczęta:',
        msg_simulation_complete: 'Symulacja zakończona',
        msg_simulation_stopped: 'Symulacja zatrzymana',
        msg_use_chrome: 'Użyj Chrome lub Edge do połączenia szeregowego',
        msg_connected: 'Połączono z maszyną',
        msg_disconnected: 'Rozłączono z maszyną',
        msg_error: 'Błąd',
        msg_emergency_stop: '⛔ AKTYWOWANO ZATRZYMANIE AWARYJNE',
        msg_not_connected: 'Nie połączono z maszyną',
        msg_starting: 'Uruchamianie zadania...',
        msg_complete: '✅ Zadanie zakończone pomyślnie',
        msg_paused: 'Zadanie wstrzymane',
        msg_resumed: 'Zadanie wznowione',
        msg_framing: 'Ramkowanie obszaru roboczego...',
        msg_profile_saved: 'Profil maszyny zapisany',
        msg_preset_applied: 'Ustawienie zastosowane',
        msg_preset_saved: 'Ustawienie zapisane',
        msg_project_saved: 'Projekt zapisany',
        msg_project_loaded: 'Projekt wczytany',
        
        home_tip: '💡 Prawy klik → "Ustaw pozycję zerową tutaj"',
        edit_mode_label: '✂️ TRYB EDYTORA ŚCIEŻEK',
        editing: 'Edycja',
        confirm_delete_all: 'Usunąć wszystkie obiekty?'
    },

    // ==========================================
    // РУССКИЙ
    // ==========================================
    ru: {
        _flag: '🇷🇺',
        _name: 'Русский',
        
        sec_project: '📁 Проект',
        sec_machine: '🔧 Станок',
        sec_home: '🏠 Начало',
        sec_import: '📁 Импорт',
        sec_vectorize: '✏️ Векторизация',
        sec_raster: '🖼️ Растр',
        sec_path_editor: '✂️ Редактор путей',
        sec_presets: '🎯 Пресеты',
        sec_objects: '📦 Объекты',
        sec_properties: '⚙️ Свойства',
        sec_jog: '🎮 Управление',
        
        btn_save: '💾 Сохранить',
        btn_load: '📂 Загрузить',
        btn_save_profile: '💾 Сохранить профиль',
        btn_set: '📍 Установить',
        btn_go: '🏠 Перейти',
        btn_import_image: '📷 Изображение/SVG',
        btn_add_text: '📝 Растровый текст',
        btn_add_vector_text: '🔤 Векторный текст',
        btn_vectorize: '🔄 Векторизовать',
        btn_raster_gcode: '📄 Растровый G-Code',
        btn_delete: '🗑️ Удалить',
        btn_delete_small: '🧹 Мелкие',
        btn_new_preset: '+ Новый',
        btn_select_all: 'Все',
        btn_clear: 'Очистить',
        btn_start: '▶️ СТАРТ',
        btn_pause: '⏸️ Пауза',
        btn_resume: '▶️ Продолжить',
        btn_exit: '✓ Выход',
        btn_send: 'Отправить',
        btn_copy: '📋 Копировать',
        btn_download: '💾 Скачать',
        btn_send_machine: '📤 Отправить',
        btn_create: '✅ Создать',
        btn_connect: 'Подключить',
        btn_disconnect: 'Отключить',
        btn_stop: 'СТОП ⛔',
        
        lbl_x_max: 'X Макс',
        lbl_y_max: 'Y Макс',
        lbl_mirror_x: 'Зеркало по X',
        lbl_mirror_y: 'Зеркало по Y',
        lbl_threshold: 'Порог',
        lbl_border_margin: 'Отступ от края',
        lbl_remove_borders: 'Удалить границы',
        lbl_resolution: 'Разрешение',
        lbl_bidirectional: 'Двунаправленный',
        lbl_objects: 'Объекты',
        lbl_width: 'Ширина',
        lbl_height: 'Высота',
        lbl_lock_ratio: 'Сохранять пропорции',
        lbl_rotation: 'Поворот',
        lbl_power: 'Мощность',
        lbl_speed: 'Скорость',
        lbl_passes: 'Проходы',
        lbl_name: 'Имя',
        lbl_text: 'Текст',
        lbl_size: 'Размер (мм)',
        lbl_lines: 'строк',
        lbl_bold: 'Жирный',
        
        ctx_set_home_here: '📍 Установить начало здесь',
        ctx_select: '✓ Выбрать',
        ctx_select_all: '☑ Выбрать всё',
        ctx_duplicate: '📋 Дублировать',
        ctx_delete: '🗑️ Удалить',
        ctx_center: '⊙ Центрировать',
        ctx_rotate_cw: '↻ Повернуть на 90° по часовой',
        ctx_rotate_ccw: '↺ Повернуть на 90° против часовой',
        ctx_flip_h: '⇄ Отразить горизонтально',
        ctx_flip_v: '⇅ Отразить вертикально',
        ctx_vectorize: '✏️ Векторизовать',
        ctx_raster_gcode: '🖼️ Растровый G-Code',
        ctx_edit_paths: '✂️ Редактировать пути',
        ctx_gcode_vector: '📄 Векторный G-Code',
        ctx_simulate: '🎬 Симуляция',
        ctx_frame: '🔲 Рамка',
        ctx_go_home: '🏠 Перейти в начало',
        
        modal_new_preset: 'Новый пресет',
        modal_add_text: 'Добавить растровый текст',
        modal_add_vector_text: 'Добавить векторный текст',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Вектор',
        tab_raster: 'Растр',
        
        sim_title: '🎬 Симуляция',
        sim_pos: 'Поз',
        sim_progress: 'Прогресс',
        sim_time: 'Время',
        sim_mode: 'Режим',
        sim_speed: 'Скорость',
        sim_mixed: 'Смешанный',
        
        tip_fit: 'Подогнать вид к рабочей области',
        tip_delete: 'Удалить выбранный объект',
        tip_duplicate: 'Дублировать выбранный объект',
        tip_rotate_cw: 'Повернуть на 90° по часовой стрелке',
        tip_rotate_ccw: 'Повернуть на 90° против часовой стрелки',
        tip_flip_h: 'Отразить горизонтально',
        tip_flip_v: 'Отразить вертикально',
        tip_gcode: 'Сгенерировать векторный G-Code',
        tip_simulate: 'Симулировать лазерную гравировку',
        tip_frame: 'Показать рамку рабочей области',
        tip_edit_paths: 'Редактировать векторные пути',
        
        status_connected: 'Подключено',
        status_disconnected: 'Отключено',
        status_ready: 'Готов',
        
        msg_processing: 'Обработка...',
        msg_home_set: 'Начальная позиция установлена',
        msg_centered: 'Центрировано в рабочей области',
        msg_rotated: 'Повёрнуто на {deg}°',
        msg_flipped_h: 'Отражено горизонтально',
        msg_flipped_v: 'Отражено вертикально',
        msg_select_vector: 'Выберите векторный объект',
        msg_path_deleted: 'Путь #{n} удалён',
        msg_small_paths_deleted: 'Удалено {n} мелких путей',
        msg_object_deleted: 'Объект удалён',
        msg_duplicated: 'Объект дублирован',
        msg_loaded: 'Загружено',
        msg_text_added: 'Растровый текст добавлен',
        msg_vector_text_added: 'Векторный текст добавлен',
        msg_no_chars: 'Нет поддерживаемых символов в тексте',
        msg_select_image: 'Выберите изображение для векторизации',
        msg_vectorizing: 'Векторизация...',
        msg_no_contours: 'Контуры не найдены',
        msg_no_paths_svg: 'Пути не найдены в SVG файле',
        msg_vectorized: '✅ Векторизовано: {n} контуров',
        msg_no_objects: 'Нет объектов в рабочей области',
        msg_gcode_generated: 'G-Code {mode}: сгенерировано {n} строк',
        msg_copied: 'Скопировано в буфер обмена!',
        msg_downloaded: 'Файл скачан!',
        msg_nothing_to_simulate: 'Нечего симулировать',
        msg_simulation_started: 'Симуляция начата:',
        msg_simulation_complete: 'Симуляция завершена',
        msg_simulation_stopped: 'Симуляция остановлена',
        msg_use_chrome: 'Используйте Chrome или Edge для последовательного подключения',
        msg_connected: 'Подключено к станку',
        msg_disconnected: 'Отключено от станка',
        msg_error: 'Ошибка',
        msg_emergency_stop: '⛔ АВАРИЙНАЯ ОСТАНОВКА АКТИВИРОВАНА',
        msg_not_connected: 'Не подключено к станку',
        msg_starting: 'Запуск задания...',
        msg_complete: '✅ Задание успешно завершено',
        msg_paused: 'Задание приостановлено',
        msg_resumed: 'Задание возобновлено',
        msg_framing: 'Обрамление рабочей области...',
        msg_profile_saved: 'Профиль станка сохранён',
        msg_preset_applied: 'Пресет применён',
        msg_preset_saved: 'Пресет сохранён',
        msg_project_saved: 'Проект сохранён',
        msg_project_loaded: 'Проект загружен',
        
        home_tip: '💡 Правый клик → "Установить начало здесь"',
        edit_mode_label: '✂️ РЕЖИМ РЕДАКТОРА ПУТЕЙ',
        editing: 'Редактирование',
        confirm_delete_all: 'Удалить все объекты?'
    },

    // ==========================================
    // 日本語
    // ==========================================
    ja: {
        _flag: '🇯🇵',
        _name: '日本語',
        
        sec_project: '📁 プロジェクト',
        sec_machine: '🔧 マシン',
        sec_home: '🏠 ホーム',
        sec_import: '📁 インポート',
        sec_vectorize: '✏️ ベクター化',
        sec_raster: '🖼️ ラスター',
        sec_path_editor: '✂️ パスエディター',
        sec_presets: '🎯 プリセット',
        sec_objects: '📦 オブジェクト',
        sec_properties: '⚙️ プロパティ',
        sec_jog: '🎮 ジョグ',
        
        btn_save: '💾 保存',
        btn_load: '📂 読み込み',
        btn_save_profile: '💾 プロファイル保存',
        btn_set: '📍 設定',
        btn_go: '🏠 移動',
        btn_import_image: '📷 画像/SVG',
        btn_add_text: '📝 ラスターテキスト',
        btn_add_vector_text: '🔤 ベクターテキスト',
        btn_vectorize: '🔄 ベクター化',
        btn_raster_gcode: '📄 ラスターG-Code',
        btn_delete: '🗑️ 削除',
        btn_delete_small: '🧹 小さいパス',
        btn_new_preset: '+ 新規',
        btn_select_all: 'すべて',
        btn_clear: 'クリア',
        btn_start: '▶️ 開始',
        btn_pause: '⏸️ 一時停止',
        btn_resume: '▶️ 再開',
        btn_exit: '✓ 終了',
        btn_send: '送信',
        btn_copy: '📋 コピー',
        btn_download: '💾 ダウンロード',
        btn_send_machine: '📤 送信',
        btn_create: '✅ 作成',
        btn_connect: '接続',
        btn_disconnect: '切断',
        btn_stop: '停止 ⛔',
        
        lbl_x_max: 'X 最大',
        lbl_y_max: 'Y 最大',
        lbl_mirror_x: 'X軸ミラー',
        lbl_mirror_y: 'Y軸ミラー',
        lbl_threshold: 'しきい値',
        lbl_border_margin: '境界マージン',
        lbl_remove_borders: '境界を削除',
        lbl_resolution: '解像度',
        lbl_bidirectional: '双方向',
        lbl_objects: 'オブジェクト',
        lbl_width: '幅',
        lbl_height: '高さ',
        lbl_lock_ratio: '縦横比を固定',
        lbl_rotation: '回転',
        lbl_power: '出力',
        lbl_speed: '速度',
        lbl_passes: 'パス数',
        lbl_name: '名前',
        lbl_text: 'テキスト',
        lbl_size: 'サイズ (mm)',
        lbl_lines: '行',
        lbl_bold: '太字',
        
        ctx_set_home_here: '📍 ここをホームに設定',
        ctx_select: '✓ 選択',
        ctx_select_all: '☑ すべて選択',
        ctx_duplicate: '📋 複製',
        ctx_delete: '🗑️ 削除',
        ctx_center: '⊙ 中央揃え',
        ctx_rotate_cw: '↻ 90°時計回り',
        ctx_rotate_ccw: '↺ 90°反時計回り',
        ctx_flip_h: '⇄ 左右反転',
        ctx_flip_v: '⇅ 上下反転',
        ctx_vectorize: '✏️ ベクター化',
        ctx_raster_gcode: '🖼️ ラスターG-Code',
        ctx_edit_paths: '✂️ パス編集',
        ctx_gcode_vector: '📄 ベクターG-Code',
        ctx_simulate: '🎬 シミュレート',
        ctx_frame: '🔲 フレーム',
        ctx_go_home: '🏠 ホームへ移動',
        
        modal_new_preset: '新規プリセット',
        modal_add_text: 'ラスターテキスト追加',
        modal_add_vector_text: 'ベクターテキスト追加',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'ベクター',
        tab_raster: 'ラスター',
        
        sim_title: '🎬 シミュレーション',
        sim_pos: '位置',
        sim_progress: '進捗',
        sim_time: '時間',
        sim_mode: 'モード',
        sim_speed: '速度',
        sim_mixed: '混合',
        
        tip_fit: 'ビューを作業領域に合わせる',
        tip_delete: '選択オブジェクトを削除',
        tip_duplicate: '選択オブジェクトを複製',
        tip_rotate_cw: '90°時計回りに回転',
        tip_rotate_ccw: '90°反時計回りに回転',
        tip_flip_h: '左右反転',
        tip_flip_v: '上下反転',
        tip_gcode: 'ベクターG-Code生成',
        tip_simulate: 'レーザー彫刻をシミュレート',
        tip_frame: '作業領域フレームを表示',
        tip_edit_paths: 'ベクターパスを編集',
        
        status_connected: '接続済み',
        status_disconnected: '切断',
        status_ready: '準備完了',
        
        msg_processing: '処理中...',
        msg_home_set: 'ホーム位置を設定',
        msg_centered: '作業領域の中央に配置',
        msg_rotated: '{deg}°に回転',
        msg_flipped_h: '左右反転しました',
        msg_flipped_v: '上下反転しました',
        msg_select_vector: 'ベクターオブジェクトを選択してください',
        msg_path_deleted: 'パス #{n} を削除',
        msg_small_paths_deleted: '{n} 個の小さなパスを削除',
        msg_object_deleted: 'オブジェクトを削除',
        msg_duplicated: 'オブジェクトを複製',
        msg_loaded: '読み込み完了',
        msg_text_added: 'ラスターテキストを追加',
        msg_vector_text_added: 'ベクターテキストを追加',
        msg_no_chars: 'サポートされている文字がありません',
        msg_select_image: 'ベクター化する画像を選択',
        msg_vectorizing: 'ベクター化中...',
        msg_no_contours: '輪郭が見つかりません',
        msg_no_paths_svg: 'SVGファイルにパスが見つかりません',
        msg_vectorized: '✅ ベクター化: {n} 輪郭',
        msg_no_objects: '作業領域にオブジェクトがありません',
        msg_gcode_generated: 'G-Code {mode}: {n} 行生成',
        msg_copied: 'クリップボードにコピーしました！',
        msg_downloaded: 'ファイルをダウンロードしました！',
        msg_nothing_to_simulate: 'シミュレートするものがありません',
        msg_simulation_started: 'シミュレーション開始:',
        msg_simulation_complete: 'シミュレーション完了',
        msg_simulation_stopped: 'シミュレーション停止',
        msg_use_chrome: 'シリアル接続にはChromeまたはEdgeを使用してください',
        msg_connected: 'マシンに接続しました',
        msg_disconnected: 'マシンから切断しました',
        msg_error: 'エラー',
        msg_emergency_stop: '⛔ 緊急停止が作動しました',
        msg_not_connected: 'マシンに接続されていません',
        msg_starting: 'ジョブを開始中...',
        msg_complete: '✅ ジョブが正常に完了しました',
        msg_paused: 'ジョブを一時停止',
        msg_resumed: 'ジョブを再開',
        msg_framing: '作業領域をフレーミング中...',
        msg_profile_saved: 'マシンプロファイルを保存',
        msg_preset_applied: 'プリセットを適用',
        msg_preset_saved: 'プリセットを保存',
        msg_project_saved: 'プロジェクトを保存',
        msg_project_loaded: 'プロジェクトを読み込み',
        
        home_tip: '💡 右クリック → "ここをホームに設定"',
        edit_mode_label: '✂️ パスエディターモード',
        editing: '編集中',
        confirm_delete_all: 'すべてのオブジェクトを削除しますか？'
    },

    // ==========================================
    // 中文
    // ==========================================
    zh: {
        _flag: '🇨🇳',
        _name: '中文',
        
        sec_project: '📁 项目',
        sec_machine: '🔧 机器',
        sec_home: '🏠 原点',
        sec_import: '📁 导入',
        sec_vectorize: '✏️ 矢量化',
        sec_raster: '🖼️ 光栅',
        sec_path_editor: '✂️ 路径编辑器',
        sec_presets: '🎯 预设',
        sec_objects: '📦 对象',
        sec_properties: '⚙️ 属性',
        sec_jog: '🎮 点动',
        
        btn_save: '💾 保存',
        btn_load: '📂 加载',
        btn_save_profile: '💾 保存配置',
        btn_set: '📍 设置',
        btn_go: '🏠 前往',
        btn_import_image: '📷 图片/SVG',
        btn_add_text: '📝 光栅文本',
        btn_add_vector_text: '🔤 矢量文本',
        btn_vectorize: '🔄 矢量化',
        btn_raster_gcode: '📄 光栅G代码',
        btn_delete: '🗑️ 删除',
        btn_delete_small: '🧹 小路径',
        btn_new_preset: '+ 新建',
        btn_select_all: '全部',
        btn_clear: '清除',
        btn_start: '▶️ 开始',
        btn_pause: '⏸️ 暂停',
        btn_resume: '▶️ 继续',
        btn_exit: '✓ 退出',
        btn_send: '发送',
        btn_copy: '📋 复制',
        btn_download: '💾 下载',
        btn_send_machine: '📤 发送',
        btn_create: '✅ 创建',
        btn_connect: '连接',
        btn_disconnect: '断开',
        btn_stop: '停止 ⛔',
        
        lbl_x_max: 'X 最大',
        lbl_y_max: 'Y 最大',
        lbl_mirror_x: 'X轴镜像',
        lbl_mirror_y: 'Y轴镜像',
        lbl_threshold: '阈值',
        lbl_border_margin: '边框边距',
        lbl_remove_borders: '移除边框',
        lbl_resolution: '分辨率',
        lbl_bidirectional: '双向',
        lbl_objects: '对象',
        lbl_width: '宽度',
        lbl_height: '高度',
        lbl_lock_ratio: '锁定比例',
        lbl_rotation: '旋转',
        lbl_power: '功率',
        lbl_speed: '速度',
        lbl_passes: '次数',
        lbl_name: '名称',
        lbl_text: '文本',
        lbl_size: '尺寸 (mm)',
        lbl_lines: '行',
        lbl_bold: '粗体',
        
        ctx_set_home_here: '📍 在此设置原点',
        ctx_select: '✓ 选择',
        ctx_select_all: '☑ 全选',
        ctx_duplicate: '📋 复制',
        ctx_delete: '🗑️ 删除',
        ctx_center: '⊙ 居中',
        ctx_rotate_cw: '↻ 顺时针旋转90°',
        ctx_rotate_ccw: '↺ 逆时针旋转90°',
        ctx_flip_h: '⇄ 水平翻转',
        ctx_flip_v: '⇅ 垂直翻转',
        ctx_vectorize: '✏️ 矢量化',
        ctx_raster_gcode: '🖼️ 光栅G代码',
        ctx_edit_paths: '✂️ 编辑路径',
        ctx_gcode_vector: '📄 矢量G代码',
        ctx_simulate: '🎬 模拟',
        ctx_frame: '🔲 边框',
        ctx_go_home: '🏠 返回原点',
        
        modal_new_preset: '新建预设',
        modal_add_text: '添加光栅文本',
        modal_add_vector_text: '添加矢量文本',
        modal_gcode: '📄 G代码',
        
        tab_vector: '矢量',
        tab_raster: '光栅',
        
        sim_title: '🎬 模拟',
        sim_pos: '位置',
        sim_progress: '进度',
        sim_time: '时间',
        sim_mode: '模式',
        sim_speed: '速度',
        sim_mixed: '混合',
        
        tip_fit: '调整视图适应工作区',
        tip_delete: '删除选中对象',
        tip_duplicate: '复制选中对象',
        tip_rotate_cw: '顺时针旋转90°',
        tip_rotate_ccw: '逆时针旋转90°',
        tip_flip_h: '水平翻转',
        tip_flip_v: '垂直翻转',
        tip_gcode: '生成矢量G代码',
        tip_simulate: '模拟激光雕刻',
        tip_frame: '显示工作区边框',
        tip_edit_paths: '编辑矢量路径',
        
        status_connected: '已连接',
        status_disconnected: '已断开',
        status_ready: '就绪',
        
        msg_processing: '处理中...',
        msg_home_set: '原点已设置',
        msg_centered: '已居中于工作区',
        msg_rotated: '已旋转至 {deg}°',
        msg_flipped_h: '已水平翻转',
        msg_flipped_v: '已垂直翻转',
        msg_select_vector: '请选择矢量对象',
        msg_path_deleted: '路径 #{n} 已删除',
        msg_small_paths_deleted: '已删除 {n} 个小路径',
        msg_object_deleted: '对象已删除',
        msg_duplicated: '对象已复制',
        msg_loaded: '已加载',
        msg_text_added: '光栅文本已添加',
        msg_vector_text_added: '矢量文本已添加',
        msg_no_chars: '文本中没有支持的字符',
        msg_select_image: '请选择要矢量化的图片',
        msg_vectorizing: '矢量化中...',
        msg_no_contours: '未找到轮廓',
        msg_no_paths_svg: 'SVG文件中未找到路径',
        msg_vectorized: '✅ 矢量化: {n} 个轮廓',
        msg_no_objects: '工作区中没有对象',
        msg_gcode_generated: 'G代码 {mode}: 已生成 {n} 行',
        msg_copied: '已复制到剪贴板！',
        msg_downloaded: '文件已下载！',
        msg_nothing_to_simulate: '没有可模拟的内容',
        msg_simulation_started: '模拟已开始:',
        msg_simulation_complete: '模拟完成',
        msg_simulation_stopped: '模拟已停止',
        msg_use_chrome: '请使用Chrome或Edge进行串口连接',
        msg_connected: '已连接到机器',
        msg_disconnected: '已从机器断开',
        msg_error: '错误',
        msg_emergency_stop: '⛔ 紧急停止已激活',
        msg_not_connected: '未连接到机器',
        msg_starting: '正在启动任务...',
        msg_complete: '✅ 任务成功完成',
        msg_paused: '任务已暂停',
        msg_resumed: '任务已恢复',
        msg_framing: '正在框选工作区...',
        msg_profile_saved: '机器配置已保存',
        msg_preset_applied: '预设已应用',
        msg_preset_saved: '预设已保存',
        msg_project_saved: '项目已保存',
        msg_project_loaded: '项目已加载',
        
        home_tip: '💡 右键点击 → "在此设置原点"',
        edit_mode_label: '✂️ 路径编辑器模式',
        editing: '编辑中',
        confirm_delete_all: '删除所有对象？'
    }

}; // End of LANG object