// ============================================
// LaserCAM Pro v6.5 - Language File
// ============================================

const LANG = {
    // ==========================================
    // ITALIANO
    // ==========================================
    it: {
        _flag: '🇮🇹',
        _name: 'Italiano',
        
        // Sections
        sec_project: '📁 Progetto',
        sec_machine: '🔧 Macchina',
        sec_home: '🏠 Home',
        sec_import: '📁 Importa',
        sec_vectorize: '✏️ Vettorizzazione',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Editor Path',
        sec_presets: '🎯 Preset',
        sec_objects: '📦 Oggetti',
        sec_properties: '⚙️ Proprietà',
        sec_jog: '🎮 Jog',
        
        // Buttons
        btn_save: '💾 Salva',
        btn_load: '📂 Carica',
        btn_save_profile: '💾 Salva Profilo',
        btn_set: '📍 Set',
        btn_go: '🏠 Vai',
        btn_import_image: '📷 Immagine/SVG',
        btn_add_text: '📝 Testo',
        btn_vectorize: '🔄 Vettorizza',
        btn_raster_gcode: '📄 G-Code Raster',
        btn_delete: '🗑️ Elimina',
        btn_delete_small: '🧹 Piccoli',
        btn_new_preset: '+ Nuovo',
        btn_select_all: 'Tutti',
        btn_clear: 'Cancella',
        btn_start: '▶️ AVVIA',
        btn_pause: '⏸️ Pausa',
        btn_resume: '▶️ Riprendi',
        btn_exit: '✓ Esci',
        btn_send: 'Invia',
        btn_copy: '📋 Copia',
        btn_download: '💾 Scarica',
        btn_send_machine: '📤 Invia',
        btn_create: '✅ Crea',
        btn_connect: 'Connetti',
        btn_disconnect: 'Disconnetti',
        btn_stop: 'STOP ⛔',
        
        // Labels
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_threshold: 'Soglia',
        lbl_border_margin: 'Margine bordo',
        lbl_remove_borders: 'Rimuovi bordi',
        lbl_resolution: 'Risoluzione',
        lbl_bidirectional: 'Bidirezionale',
        lbl_objects: 'Oggetti',
        lbl_width: 'Largh.',
        lbl_height: 'Alt.',
        lbl_lock_ratio: 'Proporzioni',
        lbl_power: 'Potenza',
        lbl_speed: 'Velocità',
        lbl_passes: 'Passate',
        lbl_name: 'Nome',
        lbl_text: 'Testo',
        lbl_size: 'Dim. (mm)',
        lbl_lines: 'linee',
        
        // Context Menu
        ctx_set_home_here: '📍 Imposta Home qui',
        ctx_select: '✓ Seleziona',
        ctx_select_all: '☑ Seleziona tutto',
        ctx_duplicate: '📋 Duplica',
        ctx_delete: '🗑️ Elimina',
        ctx_center: '⊙ Centra',
        ctx_vectorize: '✏️ Vettorizza',
        ctx_raster_gcode: '🖼️ G-Code Raster',
        ctx_edit_paths: '✂️ Modifica Path',
        ctx_gcode_vector: '📄 G-Code Vettoriale',
        ctx_simulate: '🎬 Simula',
        ctx_frame: '🔲 Frame',
        ctx_go_home: '🏠 Vai a Home',
        
        // Modals
        modal_new_preset: 'Nuovo Preset',
        modal_add_text: 'Aggiungi Testo',
        modal_gcode: '📄 G-Code',
        
        // Tabs
        tab_vector: 'Vettoriale',
        tab_raster: 'Raster',
        
        // Simulation
        sim_title: '🎬 Simulazione',
        sim_pos: 'Pos',
        sim_progress: 'Progresso',
        sim_time: 'Tempo',
        sim_mode: 'Modalità',
        sim_speed: 'Velocità',
        sim_mixed: 'Misto',
        
        // Tooltips
        tip_fit: 'Adatta vista',
        tip_delete: 'Elimina',
        tip_duplicate: 'Duplica',
        tip_gcode: 'Genera G-Code',
        tip_simulate: 'Simula incisione',
        tip_frame: 'Frame area',
        tip_edit_paths: 'Modifica path',
        
        // Status
        status_connected: 'Connesso',
        status_disconnected: 'Disconnesso',
        status_ready: 'Pronto',
        
        // Messages
        msg_processing: 'Elaborazione...',
        msg_home_set: 'Home impostata',
        msg_centered: 'Centrato',
        msg_select_vector: 'Seleziona un vettore',
        msg_path_deleted: 'Path #{n} eliminato',
        msg_small_paths_deleted: 'Rimossi {n} path piccoli',
        msg_object_deleted: 'Oggetto eliminato',
        msg_duplicated: 'Duplicato',
        msg_loaded: 'Caricato',
        msg_text_added: 'Testo aggiunto',
        msg_select_image: 'Seleziona un\'immagine',
        msg_vectorizing: 'Vettorizzazione...',
        msg_no_contours: 'Nessun contorno trovato',
        msg_vectorized: '✅ Vettorizzato: {n} contorni',
        msg_no_objects: 'Nessun oggetto',
        msg_gcode_generated: 'G-Code {mode}: {n} linee',
        msg_copied: 'Copiato!',
        msg_downloaded: 'Scaricato!',
        msg_nothing_to_simulate: 'Niente da simulare',
        msg_simulation_started: 'Simulazione avviata:',
        msg_simulation_complete: 'Simulazione completata',
        msg_simulation_stopped: 'Simulazione fermata',
        msg_use_chrome: 'Usa Chrome o Edge',
        msg_connected: 'Connesso',
        msg_disconnected: 'Disconnesso',
        msg_error: 'Errore',
        msg_emergency_stop: '⛔ STOP EMERGENZA',
        msg_not_connected: 'Non connesso',
        msg_starting: 'Avvio...',
        msg_complete: '✅ Completato',
        msg_paused: 'In pausa',
        msg_resumed: 'Ripreso',
        msg_framing: 'Frame in corso...',
        msg_profile_saved: 'Profilo salvato',
        msg_preset_applied: 'Preset applicato',
        msg_preset_saved: 'Preset salvato',
        msg_project_saved: 'Progetto salvato',
        msg_project_loaded: 'Progetto caricato',
        
        // Other
        home_tip: '💡 Tasto destro → "Imposta Home qui"',
        edit_mode_label: '✂️ EDITOR PATH',
        editing: 'Modifica',
        confirm_delete_all: 'Eliminare tutto?'
    },

    // ==========================================
    // ENGLISH
    // ==========================================
    en: {
        _flag: '🇬🇧',
        _name: 'English',
        
        sec_project: '📁 Project',
        sec_machine: '🔧 Machine',
        sec_home: '🏠 Home',
        sec_import: '📁 Import',
        sec_vectorize: '✏️ Vectorization',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Path Editor',
        sec_presets: '🎯 Presets',
        sec_objects: '📦 Objects',
        sec_properties: '⚙️ Properties',
        sec_jog: '🎮 Jog',
        
        btn_save: '💾 Save',
        btn_load: '📂 Load',
        btn_save_profile: '💾 Save Profile',
        btn_set: '📍 Set',
        btn_go: '🏠 Go',
        btn_import_image: '📷 Image/SVG',
        btn_add_text: '📝 Text',
        btn_vectorize: '🔄 Vectorize',
        btn_raster_gcode: '📄 Raster G-Code',
        btn_delete: '🗑️ Delete',
        btn_delete_small: '🧹 Small',
        btn_new_preset: '+ New',
        btn_select_all: 'All',
        btn_clear: 'Clear',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Resume',
        btn_exit: '✓ Exit',
        btn_send: 'Send',
        btn_copy: '📋 Copy',
        btn_download: '💾 Download',
        btn_send_machine: '📤 Send',
        btn_create: '✅ Create',
        btn_connect: 'Connect',
        btn_disconnect: 'Disconnect',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_threshold: 'Threshold',
        lbl_border_margin: 'Border margin',
        lbl_remove_borders: 'Remove borders',
        lbl_resolution: 'Resolution',
        lbl_bidirectional: 'Bidirectional',
        lbl_objects: 'Objects',
        lbl_width: 'Width',
        lbl_height: 'Height',
        lbl_lock_ratio: 'Lock ratio',
        lbl_power: 'Power',
        lbl_speed: 'Speed',
        lbl_passes: 'Passes',
        lbl_name: 'Name',
        lbl_text: 'Text',
        lbl_size: 'Size (mm)',
        lbl_lines: 'lines',
        
        ctx_set_home_here: '📍 Set Home here',
        ctx_select: '✓ Select',
        ctx_select_all: '☑ Select all',
        ctx_duplicate: '📋 Duplicate',
        ctx_delete: '🗑️ Delete',
        ctx_center: '⊙ Center',
        ctx_vectorize: '✏️ Vectorize',
        ctx_raster_gcode: '🖼️ Raster G-Code',
        ctx_edit_paths: '✂️ Edit Paths',
        ctx_gcode_vector: '📄 Vector G-Code',
        ctx_simulate: '🎬 Simulate',
        ctx_frame: '🔲 Frame',
        ctx_go_home: '🏠 Go to Home',
        
        modal_new_preset: 'New Preset',
        modal_add_text: 'Add Text',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vector',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Progress',
        sim_time: 'Time',
        sim_mode: 'Mode',
        sim_speed: 'Speed',
        sim_mixed: 'Mixed',
        
        tip_fit: 'Fit view',
        tip_delete: 'Delete',
        tip_duplicate: 'Duplicate',
        tip_gcode: 'Generate G-Code',
        tip_simulate: 'Simulate engraving',
        tip_frame: 'Frame area',
        tip_edit_paths: 'Edit paths',
        
        status_connected: 'Connected',
        status_disconnected: 'Disconnected',
        status_ready: 'Ready',
        
        msg_processing: 'Processing...',
        msg_home_set: 'Home set',
        msg_centered: 'Centered',
        msg_select_vector: 'Select a vector',
        msg_path_deleted: 'Path #{n} deleted',
        msg_small_paths_deleted: 'Removed {n} small paths',
        msg_object_deleted: 'Object deleted',
        msg_duplicated: 'Duplicated',
        msg_loaded: 'Loaded',
        msg_text_added: 'Text added',
        msg_select_image: 'Select an image',
        msg_vectorizing: 'Vectorizing...',
        msg_no_contours: 'No contours found',
        msg_vectorized: '✅ Vectorized: {n} contours',
        msg_no_objects: 'No objects',
        msg_gcode_generated: 'G-Code {mode}: {n} lines',
        msg_copied: 'Copied!',
        msg_downloaded: 'Downloaded!',
        msg_nothing_to_simulate: 'Nothing to simulate',
        msg_simulation_started: 'Simulation started:',
        msg_simulation_complete: 'Simulation complete',
        msg_simulation_stopped: 'Simulation stopped',
        msg_use_chrome: 'Use Chrome or Edge',
        msg_connected: 'Connected',
        msg_disconnected: 'Disconnected',
        msg_error: 'Error',
        msg_emergency_stop: '⛔ EMERGENCY STOP',
        msg_not_connected: 'Not connected',
        msg_starting: 'Starting...',
        msg_complete: '✅ Complete',
        msg_paused: 'Paused',
        msg_resumed: 'Resumed',
        msg_framing: 'Framing...',
        msg_profile_saved: 'Profile saved',
        msg_preset_applied: 'Preset applied',
        msg_preset_saved: 'Preset saved',
        msg_project_saved: 'Project saved',
        msg_project_loaded: 'Project loaded',
        
        home_tip: '💡 Right-click → "Set Home here"',
        edit_mode_label: '✂️ PATH EDITOR',
        editing: 'Editing',
        confirm_delete_all: 'Delete all?'
    },

    // ==========================================
    // FRANÇAIS
    // ==========================================
    fr: {
        _flag: '🇫🇷',
        _name: 'Français',
        
        sec_project: '📁 Projet',
        sec_machine: '🔧 Machine',
        sec_home: '🏠 Origine',
        sec_import: '📁 Importer',
        sec_vectorize: '✏️ Vectorisation',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Éditeur de tracés',
        sec_presets: '🎯 Préréglages',
        sec_objects: '📦 Objets',
        sec_properties: '⚙️ Propriétés',
        sec_jog: '🎮 Déplacement',
        
        btn_save: '💾 Sauver',
        btn_load: '📂 Charger',
        btn_save_profile: '💾 Sauver profil',
        btn_set: '📍 Définir',
        btn_go: '🏠 Aller',
        btn_import_image: '📷 Image/SVG',
        btn_add_text: '📝 Texte',
        btn_vectorize: '🔄 Vectoriser',
        btn_raster_gcode: '📄 G-Code Raster',
        btn_delete: '🗑️ Supprimer',
        btn_delete_small: '🧹 Petits',
        btn_new_preset: '+ Nouveau',
        btn_select_all: 'Tout',
        btn_clear: 'Effacer',
        btn_start: '▶️ DÉMARRER',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Reprendre',
        btn_exit: '✓ Quitter',
        btn_send: 'Envoyer',
        btn_copy: '📋 Copier',
        btn_download: '💾 Télécharger',
        btn_send_machine: '📤 Envoyer',
        btn_create: '✅ Créer',
        btn_connect: 'Connecter',
        btn_disconnect: 'Déconnecter',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_threshold: 'Seuil',
        lbl_border_margin: 'Marge bordure',
        lbl_remove_borders: 'Supprimer bordures',
        lbl_resolution: 'Résolution',
        lbl_bidirectional: 'Bidirectionnel',
        lbl_objects: 'Objets',
        lbl_width: 'Larg.',
        lbl_height: 'Haut.',
        lbl_lock_ratio: 'Proportions',
        lbl_power: 'Puissance',
        lbl_speed: 'Vitesse',
        lbl_passes: 'Passes',
        lbl_name: 'Nom',
        lbl_text: 'Texte',
        lbl_size: 'Taille (mm)',
        lbl_lines: 'lignes',
        
        ctx_set_home_here: '📍 Définir origine ici',
        ctx_select: '✓ Sélectionner',
        ctx_select_all: '☑ Tout sélectionner',
        ctx_duplicate: '📋 Dupliquer',
        ctx_delete: '🗑️ Supprimer',
        ctx_center: '⊙ Centrer',
        ctx_vectorize: '✏️ Vectoriser',
        ctx_raster_gcode: '🖼️ G-Code Raster',
        ctx_edit_paths: '✂️ Modifier tracés',
        ctx_gcode_vector: '📄 G-Code Vectoriel',
        ctx_simulate: '🎬 Simuler',
        ctx_frame: '🔲 Cadre',
        ctx_go_home: '🏠 Aller à l\'origine',
        
        modal_new_preset: 'Nouveau préréglage',
        modal_add_text: 'Ajouter du texte',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vectoriel',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Progression',
        sim_time: 'Temps',
        sim_mode: 'Mode',
        sim_speed: 'Vitesse',
        sim_mixed: 'Mixte',
        
        tip_fit: 'Ajuster la vue',
        tip_delete: 'Supprimer',
        tip_duplicate: 'Dupliquer',
        tip_gcode: 'Générer G-Code',
        tip_simulate: 'Simuler gravure',
        tip_frame: 'Cadrer zone',
        tip_edit_paths: 'Modifier tracés',
        
        status_connected: 'Connecté',
        status_disconnected: 'Déconnecté',
        status_ready: 'Prêt',
        
        msg_processing: 'Traitement...',
        msg_home_set: 'Origine définie',
        msg_centered: 'Centré',
        msg_select_vector: 'Sélectionnez un vecteur',
        msg_path_deleted: 'Tracé #{n} supprimé',
        msg_small_paths_deleted: '{n} petits tracés supprimés',
        msg_object_deleted: 'Objet supprimé',
        msg_duplicated: 'Dupliqué',
        msg_loaded: 'Chargé',
        msg_text_added: 'Texte ajouté',
        msg_select_image: 'Sélectionnez une image',
        msg_vectorizing: 'Vectorisation...',
        msg_no_contours: 'Aucun contour trouvé',
        msg_vectorized: '✅ Vectorisé: {n} contours',
        msg_no_objects: 'Aucun objet',
        msg_gcode_generated: 'G-Code {mode}: {n} lignes',
        msg_copied: 'Copié!',
        msg_downloaded: 'Téléchargé!',
        msg_nothing_to_simulate: 'Rien à simuler',
        msg_simulation_started: 'Simulation démarrée:',
        msg_simulation_complete: 'Simulation terminée',
        msg_simulation_stopped: 'Simulation arrêtée',
        msg_use_chrome: 'Utilisez Chrome ou Edge',
        msg_connected: 'Connecté',
        msg_disconnected: 'Déconnecté',
        msg_error: 'Erreur',
        msg_emergency_stop: '⛔ ARRÊT D\'URGENCE',
        msg_not_connected: 'Non connecté',
        msg_starting: 'Démarrage...',
        msg_complete: '✅ Terminé',
        msg_paused: 'En pause',
        msg_resumed: 'Repris',
        msg_framing: 'Cadrage...',
        msg_profile_saved: 'Profil sauvegardé',
        msg_preset_applied: 'Préréglage appliqué',
        msg_preset_saved: 'Préréglage sauvegardé',
        msg_project_saved: 'Projet sauvegardé',
        msg_project_loaded: 'Projet chargé',
        
        home_tip: '💡 Clic droit → "Définir origine ici"',
        edit_mode_label: '✂️ ÉDITEUR DE TRACÉS',
        editing: 'Édition',
        confirm_delete_all: 'Tout supprimer?'
    },

    // ==========================================
    // DEUTSCH
    // ==========================================
    de: {
        _flag: '🇩🇪',
        _name: 'Deutsch',
        
        sec_project: '📁 Projekt',
        sec_machine: '🔧 Maschine',
        sec_home: '🏠 Nullpunkt',
        sec_import: '📁 Importieren',
        sec_vectorize: '✏️ Vektorisierung',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Pfad-Editor',
        sec_presets: '🎯 Voreinstellungen',
        sec_objects: '📦 Objekte',
        sec_properties: '⚙️ Eigenschaften',
        sec_jog: '🎮 Steuerung',
        
        btn_save: '💾 Speichern',
        btn_load: '📂 Laden',
        btn_save_profile: '💾 Profil speichern',
        btn_set: '📍 Setzen',
        btn_go: '🏠 Fahren',
        btn_import_image: '📷 Bild/SVG',
        btn_add_text: '📝 Text',
        btn_vectorize: '🔄 Vektorisieren',
        btn_raster_gcode: '📄 Raster G-Code',
        btn_delete: '🗑️ Löschen',
        btn_delete_small: '🧹 Kleine',
        btn_new_preset: '+ Neu',
        btn_select_all: 'Alle',
        btn_clear: 'Löschen',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Fortsetzen',
        btn_exit: '✓ Beenden',
        btn_send: 'Senden',
        btn_copy: '📋 Kopieren',
        btn_download: '💾 Download',
        btn_send_machine: '📤 Senden',
        btn_create: '✅ Erstellen',
        btn_connect: 'Verbinden',
        btn_disconnect: 'Trennen',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Max',
        lbl_y_max: 'Y Max',
        lbl_threshold: 'Schwellenwert',
        lbl_border_margin: 'Randabstand',
        lbl_remove_borders: 'Ränder entfernen',
        lbl_resolution: 'Auflösung',
        lbl_bidirectional: 'Bidirektional',
        lbl_objects: 'Objekte',
        lbl_width: 'Breite',
        lbl_height: 'Höhe',
        lbl_lock_ratio: 'Proportionen',
        lbl_power: 'Leistung',
        lbl_speed: 'Geschwindigkeit',
        lbl_passes: 'Durchgänge',
        lbl_name: 'Name',
        lbl_text: 'Text',
        lbl_size: 'Größe (mm)',
        lbl_lines: 'Zeilen',
        
        ctx_set_home_here: '📍 Nullpunkt hier setzen',
        ctx_select: '✓ Auswählen',
        ctx_select_all: '☑ Alles auswählen',
        ctx_duplicate: '📋 Duplizieren',
        ctx_delete: '🗑️ Löschen',
        ctx_center: '⊙ Zentrieren',
        ctx_vectorize: '✏️ Vektorisieren',
        ctx_raster_gcode: '🖼️ Raster G-Code',
        ctx_edit_paths: '✂️ Pfade bearbeiten',
        ctx_gcode_vector: '📄 Vektor G-Code',
        ctx_simulate: '🎬 Simulieren',
        ctx_frame: '🔲 Rahmen',
        ctx_go_home: '🏠 Zum Nullpunkt',
        
        modal_new_preset: 'Neue Voreinstellung',
        modal_add_text: 'Text hinzufügen',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vektor',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulation',
        sim_pos: 'Pos',
        sim_progress: 'Fortschritt',
        sim_time: 'Zeit',
        sim_mode: 'Modus',
        sim_speed: 'Geschwindigkeit',
        sim_mixed: 'Gemischt',
        
        tip_fit: 'Ansicht anpassen',
        tip_delete: 'Löschen',
        tip_duplicate: 'Duplizieren',
        tip_gcode: 'G-Code generieren',
        tip_simulate: 'Gravur simulieren',
        tip_frame: 'Bereich rahmen',
        tip_edit_paths: 'Pfade bearbeiten',
        
        status_connected: 'Verbunden',
        status_disconnected: 'Getrennt',
        status_ready: 'Bereit',
        
        msg_processing: 'Verarbeitung...',
        msg_home_set: 'Nullpunkt gesetzt',
        msg_centered: 'Zentriert',
        msg_select_vector: 'Wählen Sie einen Vektor',
        msg_path_deleted: 'Pfad #{n} gelöscht',
        msg_small_paths_deleted: '{n} kleine Pfade entfernt',
        msg_object_deleted: 'Objekt gelöscht',
        msg_duplicated: 'Dupliziert',
        msg_loaded: 'Geladen',
        msg_text_added: 'Text hinzugefügt',
        msg_select_image: 'Wählen Sie ein Bild',
        msg_vectorizing: 'Vektorisierung...',
        msg_no_contours: 'Keine Konturen gefunden',
        msg_vectorized: '✅ Vektorisiert: {n} Konturen',
        msg_no_objects: 'Keine Objekte',
        msg_gcode_generated: 'G-Code {mode}: {n} Zeilen',
        msg_copied: 'Kopiert!',
        msg_downloaded: 'Heruntergeladen!',
        msg_nothing_to_simulate: 'Nichts zu simulieren',
        msg_simulation_started: 'Simulation gestartet:',
        msg_simulation_complete: 'Simulation abgeschlossen',
        msg_simulation_stopped: 'Simulation gestoppt',
        msg_use_chrome: 'Verwenden Sie Chrome oder Edge',
        msg_connected: 'Verbunden',
        msg_disconnected: 'Getrennt',
        msg_error: 'Fehler',
        msg_emergency_stop: '⛔ NOT-STOPP',
        msg_not_connected: 'Nicht verbunden',
        msg_starting: 'Starte...',
        msg_complete: '✅ Fertig',
        msg_paused: 'Pausiert',
        msg_resumed: 'Fortgesetzt',
        msg_framing: 'Rahmen...',
        msg_profile_saved: 'Profil gespeichert',
        msg_preset_applied: 'Voreinstellung angewendet',
        msg_preset_saved: 'Voreinstellung gespeichert',
        msg_project_saved: 'Projekt gespeichert',
        msg_project_loaded: 'Projekt geladen',
        
        home_tip: '💡 Rechtsklick → "Nullpunkt hier setzen"',
        edit_mode_label: '✂️ PFAD-EDITOR',
        editing: 'Bearbeitung',
        confirm_delete_all: 'Alles löschen?'
    },

    // ==========================================
    // ESPAÑOL
    // ==========================================
    es: {
        _flag: '🇪🇸',
        _name: 'Español',
        
        sec_project: '📁 Proyecto',
        sec_machine: '🔧 Máquina',
        sec_home: '🏠 Origen',
        sec_import: '📁 Importar',
        sec_vectorize: '✏️ Vectorización',
        sec_raster: '🖼️ Ráster',
        sec_path_editor: '✂️ Editor de trazados',
        sec_presets: '🎯 Preajustes',
        sec_objects: '📦 Objetos',
        sec_properties: '⚙️ Propiedades',
        sec_jog: '🎮 Control',
        
        btn_save: '💾 Guardar',
        btn_load: '📂 Cargar',
        btn_save_profile: '💾 Guardar perfil',
        btn_set: '📍 Establecer',
        btn_go: '🏠 Ir',
        btn_import_image: '📷 Imagen/SVG',
        btn_add_text: '📝 Texto',
        btn_vectorize: '🔄 Vectorizar',
        btn_raster_gcode: '📄 G-Code Ráster',
        btn_delete: '🗑️ Eliminar',
        btn_delete_small: '🧹 Pequeños',
        btn_new_preset: '+ Nuevo',
        btn_select_all: 'Todos',
        btn_clear: 'Borrar',
        btn_start: '▶️ INICIAR',
        btn_pause: '⏸️ Pausa',
        btn_resume: '▶️ Reanudar',
        btn_exit: '✓ Salir',
        btn_send: 'Enviar',
        btn_copy: '📋 Copiar',
        btn_download: '💾 Descargar',
        btn_send_machine: '📤 Enviar',
        btn_create: '✅ Crear',
        btn_connect: 'Conectar',
        btn_disconnect: 'Desconectar',
        btn_stop: 'PARAR ⛔',
        
        lbl_x_max: 'X Máx',
        lbl_y_max: 'Y Máx',
        lbl_threshold: 'Umbral',
        lbl_border_margin: 'Margen borde',
        lbl_remove_borders: 'Eliminar bordes',
        lbl_resolution: 'Resolución',
        lbl_bidirectional: 'Bidireccional',
        lbl_objects: 'Objetos',
        lbl_width: 'Ancho',
        lbl_height: 'Alto',
        lbl_lock_ratio: 'Proporciones',
        lbl_power: 'Potencia',
        lbl_speed: 'Velocidad',
        lbl_passes: 'Pasadas',
        lbl_name: 'Nombre',
        lbl_text: 'Texto',
        lbl_size: 'Tamaño (mm)',
        lbl_lines: 'líneas',
        
        ctx_set_home_here: '📍 Establecer origen aquí',
        ctx_select: '✓ Seleccionar',
        ctx_select_all: '☑ Seleccionar todo',
        ctx_duplicate: '📋 Duplicar',
        ctx_delete: '🗑️ Eliminar',
        ctx_center: '⊙ Centrar',
        ctx_vectorize: '✏️ Vectorizar',
        ctx_raster_gcode: '🖼️ G-Code Ráster',
        ctx_edit_paths: '✂️ Editar trazados',
        ctx_gcode_vector: '📄 G-Code Vectorial',
        ctx_simulate: '🎬 Simular',
        ctx_frame: '🔲 Marco',
        ctx_go_home: '🏠 Ir al origen',
        
        modal_new_preset: 'Nuevo preajuste',
        modal_add_text: 'Añadir texto',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vectorial',
        tab_raster: 'Ráster',
        
        sim_title: '🎬 Simulación',
        sim_pos: 'Pos',
        sim_progress: 'Progreso',
        sim_time: 'Tiempo',
        sim_mode: 'Modo',
        sim_speed: 'Velocidad',
        sim_mixed: 'Mixto',
        
        tip_fit: 'Ajustar vista',
        tip_delete: 'Eliminar',
        tip_duplicate: 'Duplicar',
        tip_gcode: 'Generar G-Code',
        tip_simulate: 'Simular grabado',
        tip_frame: 'Enmarcar área',
        tip_edit_paths: 'Editar trazados',
        
        status_connected: 'Conectado',
        status_disconnected: 'Desconectado',
        status_ready: 'Listo',
        
        msg_processing: 'Procesando...',
        msg_home_set: 'Origen establecido',
        msg_centered: 'Centrado',
        msg_select_vector: 'Seleccione un vector',
        msg_path_deleted: 'Trazado #{n} eliminado',
        msg_small_paths_deleted: '{n} trazados pequeños eliminados',
        msg_object_deleted: 'Objeto eliminado',
        msg_duplicated: 'Duplicado',
        msg_loaded: 'Cargado',
        msg_text_added: 'Texto añadido',
        msg_select_image: 'Seleccione una imagen',
        msg_vectorizing: 'Vectorizando...',
        msg_no_contours: 'No se encontraron contornos',
        msg_vectorized: '✅ Vectorizado: {n} contornos',
        msg_no_objects: 'Sin objetos',
        msg_gcode_generated: 'G-Code {mode}: {n} líneas',
        msg_copied: '¡Copiado!',
        msg_downloaded: '¡Descargado!',
        msg_nothing_to_simulate: 'Nada que simular',
        msg_simulation_started: 'Simulación iniciada:',
        msg_simulation_complete: 'Simulación completada',
        msg_simulation_stopped: 'Simulación detenida',
        msg_use_chrome: 'Use Chrome o Edge',
        msg_connected: 'Conectado',
        msg_disconnected: 'Desconectado',
        msg_error: 'Error',
        msg_emergency_stop: '⛔ PARADA DE EMERGENCIA',
        msg_not_connected: 'No conectado',
        msg_starting: 'Iniciando...',
        msg_complete: '✅ Completado',
        msg_paused: 'Pausado',
        msg_resumed: 'Reanudado',
        msg_framing: 'Enmarcando...',
        msg_profile_saved: 'Perfil guardado',
        msg_preset_applied: 'Preajuste aplicado',
        msg_preset_saved: 'Preajuste guardado',
        msg_project_saved: 'Proyecto guardado',
        msg_project_loaded: 'Proyecto cargado',
        
        home_tip: '💡 Clic derecho → "Establecer origen aquí"',
        edit_mode_label: '✂️ EDITOR DE TRAZADOS',
        editing: 'Editando',
        confirm_delete_all: '¿Eliminar todo?'
    },

    // ==========================================
    // PORTUGUÊS
    // ==========================================
    pt: {
        _flag: '🇧🇷',
        _name: 'Português',
        
        sec_project: '📁 Projeto',
        sec_machine: '🔧 Máquina',
        sec_home: '🏠 Origem',
        sec_import: '📁 Importar',
        sec_vectorize: '✏️ Vetorização',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Editor de caminhos',
        sec_presets: '🎯 Predefinições',
        sec_objects: '📦 Objetos',
        sec_properties: '⚙️ Propriedades',
        sec_jog: '🎮 Controle',
        
        btn_save: '💾 Salvar',
        btn_load: '📂 Carregar',
        btn_save_profile: '💾 Salvar perfil',
        btn_set: '📍 Definir',
        btn_go: '🏠 Ir',
        btn_import_image: '📷 Imagem/SVG',
        btn_add_text: '📝 Texto',
        btn_vectorize: '🔄 Vetorizar',
        btn_raster_gcode: '📄 G-Code Raster',
        btn_delete: '🗑️ Excluir',
        btn_delete_small: '🧹 Pequenos',
        btn_new_preset: '+ Novo',
        btn_select_all: 'Todos',
        btn_clear: 'Limpar',
        btn_start: '▶️ INICIAR',
        btn_pause: '⏸️ Pausar',
        btn_resume: '▶️ Retomar',
        btn_exit: '✓ Sair',
        btn_send: 'Enviar',
        btn_copy: '📋 Copiar',
        btn_download: '💾 Baixar',
        btn_send_machine: '📤 Enviar',
        btn_create: '✅ Criar',
        btn_connect: 'Conectar',
        btn_disconnect: 'Desconectar',
        btn_stop: 'PARAR ⛔',
        
        lbl_x_max: 'X Máx',
        lbl_y_max: 'Y Máx',
        lbl_threshold: 'Limiar',
        lbl_border_margin: 'Margem da borda',
        lbl_remove_borders: 'Remover bordas',
        lbl_resolution: 'Resolução',
        lbl_bidirectional: 'Bidirecional',
        lbl_objects: 'Objetos',
        lbl_width: 'Largura',
        lbl_height: 'Altura',
        lbl_lock_ratio: 'Proporções',
        lbl_power: 'Potência',
        lbl_speed: 'Velocidade',
        lbl_passes: 'Passadas',
        lbl_name: 'Nome',
        lbl_text: 'Texto',
        lbl_size: 'Tamanho (mm)',
        lbl_lines: 'linhas',
        
        ctx_set_home_here: '📍 Definir origem aqui',
        ctx_select: '✓ Selecionar',
        ctx_select_all: '☑ Selecionar tudo',
        ctx_duplicate: '📋 Duplicar',
        ctx_delete: '🗑️ Excluir',
        ctx_center: '⊙ Centralizar',
        ctx_vectorize: '✏️ Vetorizar',
        ctx_raster_gcode: '🖼️ G-Code Raster',
        ctx_edit_paths: '✂️ Editar caminhos',
        ctx_gcode_vector: '📄 G-Code Vetorial',
        ctx_simulate: '🎬 Simular',
        ctx_frame: '🔲 Moldura',
        ctx_go_home: '🏠 Ir para origem',
        
        modal_new_preset: 'Nova predefinição',
        modal_add_text: 'Adicionar texto',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vetorial',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulação',
        sim_pos: 'Pos',
        sim_progress: 'Progresso',
        sim_time: 'Tempo',
        sim_mode: 'Modo',
        sim_speed: 'Velocidade',
        sim_mixed: 'Misto',
        
        tip_fit: 'Ajustar vista',
        tip_delete: 'Excluir',
        tip_duplicate: 'Duplicar',
        tip_gcode: 'Gerar G-Code',
        tip_simulate: 'Simular gravação',
        tip_frame: 'Enquadrar área',
        tip_edit_paths: 'Editar caminhos',
        
        status_connected: 'Conectado',
        status_disconnected: 'Desconectado',
        status_ready: 'Pronto',
        
        msg_processing: 'Processando...',
        msg_home_set: 'Origem definida',
        msg_centered: 'Centralizado',
        msg_select_vector: 'Selecione um vetor',
        msg_path_deleted: 'Caminho #{n} excluído',
        msg_small_paths_deleted: '{n} caminhos pequenos removidos',
        msg_object_deleted: 'Objeto excluído',
        msg_duplicated: 'Duplicado',
        msg_loaded: 'Carregado',
        msg_text_added: 'Texto adicionado',
        msg_select_image: 'Selecione uma imagem',
        msg_vectorizing: 'Vetorizando...',
        msg_no_contours: 'Nenhum contorno encontrado',
        msg_vectorized: '✅ Vetorizado: {n} contornos',
        msg_no_objects: 'Sem objetos',
        msg_gcode_generated: 'G-Code {mode}: {n} linhas',
        msg_copied: 'Copiado!',
        msg_downloaded: 'Baixado!',
        msg_nothing_to_simulate: 'Nada para simular',
        msg_simulation_started: 'Simulação iniciada:',
        msg_simulation_complete: 'Simulação concluída',
        msg_simulation_stopped: 'Simulação parada',
        msg_use_chrome: 'Use Chrome ou Edge',
        msg_connected: 'Conectado',
        msg_disconnected: 'Desconectado',
        msg_error: 'Erro',
        msg_emergency_stop: '⛔ PARADA DE EMERGÊNCIA',
        msg_not_connected: 'Não conectado',
        msg_starting: 'Iniciando...',
        msg_complete: '✅ Concluído',
        msg_paused: 'Pausado',
        msg_resumed: 'Retomado',
        msg_framing: 'Enquadrando...',
        msg_profile_saved: 'Perfil salvo',
        msg_preset_applied: 'Predefinição aplicada',
        msg_preset_saved: 'Predefinição salva',
        msg_project_saved: 'Projeto salvo',
        msg_project_loaded: 'Projeto carregado',
        
        home_tip: '💡 Clique direito → "Definir origem aqui"',
        edit_mode_label: '✂️ EDITOR DE CAMINHOS',
        editing: 'Editando',
        confirm_delete_all: 'Excluir tudo?'
    },

    // ==========================================
    // DANSK
    // ==========================================
    da: {
        _flag: '🇩🇰',
        _name: 'Dansk',
        
        sec_project: '📁 Projekt',
        sec_machine: '🔧 Maskine',
        sec_home: '🏠 Nulpunkt',
        sec_import: '📁 Importer',
        sec_vectorize: '✏️ Vektorisering',
        sec_raster: '🖼️ Raster',
        sec_path_editor: '✂️ Sti-editor',
        sec_presets: '🎯 Forudindstillinger',
        sec_objects: '📦 Objekter',
        sec_properties: '⚙️ Egenskaber',
        sec_jog: '🎮 Styring',
        
        btn_save: '💾 Gem',
        btn_load: '📂 Indlæs',
        btn_save_profile: '💾 Gem profil',
        btn_set: '📍 Sæt',
        btn_go: '🏠 Gå',
        btn_import_image: '📷 Billede/SVG',
        btn_add_text: '📝 Tekst',
        btn_vectorize: '🔄 Vektoriser',
        btn_raster_gcode: '📄 Raster G-Code',
        btn_delete: '🗑️ Slet',
        btn_delete_small: '🧹 Små',
        btn_new_preset: '+ Ny',
        btn_select_all: 'Alle',
        btn_clear: 'Ryd',
        btn_start: '▶️ START',
        btn_pause: '⏸️ Pause',
        btn_resume: '▶️ Genoptag',
        btn_exit: '✓ Afslut',
        btn_send: 'Send',
        btn_copy: '📋 Kopier',
        btn_download: '💾 Download',
        btn_send_machine: '📤 Send',
        btn_create: '✅ Opret',
        btn_connect: 'Forbind',
        btn_disconnect: 'Afbryd',
        btn_stop: 'STOP ⛔',
        
        lbl_x_max: 'X Maks',
        lbl_y_max: 'Y Maks',
        lbl_threshold: 'Tærskel',
        lbl_border_margin: 'Kantmargin',
        lbl_remove_borders: 'Fjern kanter',
        lbl_resolution: 'Opløsning',
        lbl_bidirectional: 'Tovejs',
        lbl_objects: 'Objekter',
        lbl_width: 'Bredde',
        lbl_height: 'Højde',
        lbl_lock_ratio: 'Proportioner',
        lbl_power: 'Effekt',
        lbl_speed: 'Hastighed',
        lbl_passes: 'Gennemløb',
        lbl_name: 'Navn',
        lbl_text: 'Tekst',
        lbl_size: 'Størrelse (mm)',
        lbl_lines: 'linjer',
        
        ctx_set_home_here: '📍 Sæt nulpunkt her',
        ctx_select: '✓ Vælg',
        ctx_select_all: '☑ Vælg alle',
        ctx_duplicate: '📋 Dupliker',
        ctx_delete: '🗑️ Slet',
        ctx_center: '⊙ Centrer',
        ctx_vectorize: '✏️ Vektoriser',
        ctx_raster_gcode: '🖼️ Raster G-Code',
        ctx_edit_paths: '✂️ Rediger stier',
        ctx_gcode_vector: '📄 Vektor G-Code',
        ctx_simulate: '🎬 Simuler',
        ctx_frame: '🔲 Ramme',
        ctx_go_home: '🏠 Gå til nulpunkt',
        
        modal_new_preset: 'Ny forudindstilling',
        modal_add_text: 'Tilføj tekst',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Vektor',
        tab_raster: 'Raster',
        
        sim_title: '🎬 Simulering',
        sim_pos: 'Pos',
        sim_progress: 'Fremgang',
        sim_time: 'Tid',
        sim_mode: 'Tilstand',
        sim_speed: 'Hastighed',
        sim_mixed: 'Blandet',
        
        tip_fit: 'Tilpas visning',
        tip_delete: 'Slet',
        tip_duplicate: 'Dupliker',
        tip_gcode: 'Generer G-Code',
        tip_simulate: 'Simuler gravering',
        tip_frame: 'Ram område',
        tip_edit_paths: 'Rediger stier',
        
        status_connected: 'Forbundet',
        status_disconnected: 'Afbrudt',
        status_ready: 'Klar',
        
        msg_processing: 'Behandler...',
        msg_home_set: 'Nulpunkt sat',
        msg_centered: 'Centreret',
        msg_select_vector: 'Vælg en vektor',
        msg_path_deleted: 'Sti #{n} slettet',
        msg_small_paths_deleted: '{n} små stier fjernet',
        msg_object_deleted: 'Objekt slettet',
        msg_duplicated: 'Duplikeret',
        msg_loaded: 'Indlæst',
        msg_text_added: 'Tekst tilføjet',
        msg_select_image: 'Vælg et billede',
        msg_vectorizing: 'Vektoriserer...',
        msg_no_contours: 'Ingen konturer fundet',
        msg_vectorized: '✅ Vektoriseret: {n} konturer',
        msg_no_objects: 'Ingen objekter',
        msg_gcode_generated: 'G-Code {mode}: {n} linjer',
        msg_copied: 'Kopieret!',
        msg_downloaded: 'Downloadet!',
        msg_nothing_to_simulate: 'Intet at simulere',
        msg_simulation_started: 'Simulering startet:',
        msg_simulation_complete: 'Simulering færdig',
        msg_simulation_stopped: 'Simulering stoppet',
        msg_use_chrome: 'Brug Chrome eller Edge',
        msg_connected: 'Forbundet',
        msg_disconnected: 'Afbrudt',
        msg_error: 'Fejl',
        msg_emergency_stop: '⛔ NØDSTOP',
        msg_not_connected: 'Ikke forbundet',
        msg_starting: 'Starter...',
        msg_complete: '✅ Færdig',
        msg_paused: 'Pauset',
        msg_resumed: 'Genoptaget',
        msg_framing: 'Rammer...',
        msg_profile_saved: 'Profil gemt',
        msg_preset_applied: 'Forudindstilling anvendt',
        msg_preset_saved: 'Forudindstilling gemt',
        msg_project_saved: 'Projekt gemt',
        msg_project_loaded: 'Projekt indlæst',
        
        home_tip: '💡 Højreklik → "Sæt nulpunkt her"',
        edit_mode_label: '✂️ STI-EDITOR',
        editing: 'Redigerer',
        confirm_delete_all: 'Slet alt?'
    },

    // ==========================================
    // РУССКИЙ
    // ==========================================
    ru: {
        _flag: '🇷🇺',
        _name: 'Русский',
        
        sec_project: '📁 Проект',
        sec_machine: '🔧 Станок',
        sec_home: '🏠 Начало',
        sec_import: '📁 Импорт',
        sec_vectorize: '✏️ Векторизация',
        sec_raster: '🖼️ Растр',
        sec_path_editor: '✂️ Редактор путей',
        sec_presets: '🎯 Пресеты',
        sec_objects: '📦 Объекты',
        sec_properties: '⚙️ Свойства',
        sec_jog: '🎮 Управление',
        
        btn_save: '💾 Сохранить',
        btn_load: '📂 Загрузить',
        btn_save_profile: '💾 Сохранить профиль',
        btn_set: '📍 Установить',
        btn_go: '🏠 Перейти',
        btn_import_image: '📷 Изображение/SVG',
        btn_add_text: '📝 Текст',
        btn_vectorize: '🔄 Векторизовать',
        btn_raster_gcode: '📄 Растровый G-Code',
        btn_delete: '🗑️ Удалить',
        btn_delete_small: '🧹 Мелкие',
        btn_new_preset: '+ Новый',
        btn_select_all: 'Все',
        btn_clear: 'Очистить',
        btn_start: '▶️ СТАРТ',
        btn_pause: '⏸️ Пауза',
        btn_resume: '▶️ Продолжить',
        btn_exit: '✓ Выход',
        btn_send: 'Отправить',
        btn_copy: '📋 Копировать',
        btn_download: '💾 Скачать',
        btn_send_machine: '📤 Отправить',
        btn_create: '✅ Создать',
        btn_connect: 'Подключить',
        btn_disconnect: 'Отключить',
        btn_stop: 'СТОП ⛔',
        
        lbl_x_max: 'X Макс',
        lbl_y_max: 'Y Макс',
        lbl_threshold: 'Порог',
        lbl_border_margin: 'Отступ от края',
        lbl_remove_borders: 'Убрать границы',
        lbl_resolution: 'Разрешение',
        lbl_bidirectional: 'Двунаправленный',
        lbl_objects: 'Объекты',
        lbl_width: 'Ширина',
        lbl_height: 'Высота',
        lbl_lock_ratio: 'Пропорции',
        lbl_power: 'Мощность',
        lbl_speed: 'Скорость',
        lbl_passes: 'Проходы',
        lbl_name: 'Название',
        lbl_text: 'Текст',
        lbl_size: 'Размер (мм)',
        lbl_lines: 'строк',
        
        ctx_set_home_here: '📍 Установить начало здесь',
        ctx_select: '✓ Выбрать',
        ctx_select_all: '☑ Выбрать всё',
        ctx_duplicate: '📋 Дублировать',
        ctx_delete: '🗑️ Удалить',
        ctx_center: '⊙ Центрировать',
        ctx_vectorize: '✏️ Векторизовать',
        ctx_raster_gcode: '🖼️ Растровый G-Code',
        ctx_edit_paths: '✂️ Редактировать пути',
        ctx_gcode_vector: '📄 Векторный G-Code',
        ctx_simulate: '🎬 Симулировать',
        ctx_frame: '🔲 Рамка',
        ctx_go_home: '🏠 Перейти к началу',
        
        modal_new_preset: 'Новый пресет',
        modal_add_text: 'Добавить текст',
        modal_gcode: '📄 G-Code',
        
        tab_vector: 'Векторный',
        tab_raster: 'Растровый',
        
        sim_title: '🎬 Симуляция',
        sim_pos: 'Поз',
        sim_progress: 'Прогресс',
        sim_time: 'Время',
        sim_mode: 'Режим',
        sim_speed: 'Скорость',
        sim_mixed: 'Смешанный',
        
        tip_fit: 'Подогнать вид',
        tip_delete: 'Удалить',
        tip_duplicate: 'Дублировать',
        tip_gcode: 'Создать G-Code',
        tip_simulate: 'Симулировать гравировку',
        tip_frame: 'Обрамить область',
        tip_edit_paths: 'Редактировать пути',
        
        status_connected: 'Подключено',
        status_disconnected: 'Отключено',
        status_ready: 'Готово',
        
        msg_processing: 'Обработка...',
        msg_home_set: 'Начало установлено',
        msg_centered: 'Центрировано',
        msg_select_vector: 'Выберите вектор',
        msg_path_deleted: 'Путь #{n} удалён',
        msg_small_paths_deleted: 'Удалено {n} мелких путей',
        msg_object_deleted: 'Объект удалён',
        msg_duplicated: 'Дублировано',
        msg_loaded: 'Загружено',
        msg_text_added: 'Текст добавлен',
        msg_select_image: 'Выберите изображение',
        msg_vectorizing: 'Векторизация...',
        msg_no_contours: 'Контуры не найдены',
        msg_vectorized: '✅ Векторизовано: {n} контуров',
        msg_no_objects: 'Нет объектов',
        msg_gcode_generated: 'G-Code {mode}: {n} строк',
        msg_copied: 'Скопировано!',
        msg_downloaded: 'Скачано!',
        msg_nothing_to_simulate: 'Нечего симулировать',
        msg_simulation_started: 'Симуляция начата:',
        msg_simulation_complete: 'Симуляция завершена',
        msg_simulation_stopped: 'Симуляция остановлена',
        msg_use_chrome: 'Используйте Chrome или Edge',
        msg_connected: 'Подключено',
        msg_disconnected: 'Отключено',
        msg_error: 'Ошибка',
        msg_emergency_stop: '⛔ АВАРИЙНАЯ ОСТАНОВКА',
        msg_not_connected: 'Не подключено',
        msg_starting: 'Запуск...',
        msg_complete: '✅ Завершено',
        msg_paused: 'Пауза',
        msg_resumed: 'Продолжено',
        msg_framing: 'Обрамление...',
        msg_profile_saved: 'Профиль сохранён',
        msg_preset_applied: 'Пресет применён',
        msg_preset_saved: 'Пресет сохранён',
        msg_project_saved: 'Проект сохранён',
        msg_project_loaded: 'Проект загружен',
        
        home_tip: '💡 ПКМ → "Установить начало здесь"',
        edit_mode_label: '✂️ РЕДАКТОР ПУТЕЙ',
        editing: 'Редактирование',
        confirm_delete_all: 'Удалить всё?'
    },

    // ==========================================
    // 中文 (CHINESE)
    // ==========================================
    zh: {
        _flag: '🇨🇳',
        _name: '中文',
        
        sec_project: '📁 项目',
        sec_machine: '🔧 机器',
        sec_home: '🏠 原点',
        sec_import: '📁 导入',
        sec_vectorize: '✏️ 矢量化',
        sec_raster: '🖼️ 光栅',
        sec_path_editor: '✂️ 路径编辑器',
        sec_presets: '🎯 预设',
        sec_objects: '📦 对象',
        sec_properties: '⚙️ 属性',
        sec_jog: '🎮 点动',
        
        btn_save: '💾 保存',
        btn_load: '📂 加载',
        btn_save_profile: '💾 保存配置',
        btn_set: '📍 设置',
        btn_go: '🏠 前往',
        btn_import_image: '📷 图片/SVG',
        btn_add_text: '📝 文字',
        btn_vectorize: '🔄 矢量化',
        btn_raster_gcode: '📄 光栅G代码',
        btn_delete: '🗑️ 删除',
        btn_delete_small: '🧹 小路径',
        btn_new_preset: '+ 新建',
        btn_select_all: '全选',
        btn_clear: '清除',
        btn_start: '▶️ 开始',
        btn_pause: '⏸️ 暂停',
        btn_resume: '▶️ 继续',
        btn_exit: '✓ 退出',
        btn_send: '发送',
        btn_copy: '📋 复制',
        btn_download: '💾 下载',
        btn_send_machine: '📤 发送',
        btn_create: '✅ 创建',
        btn_connect: '连接',
        btn_disconnect: '断开',
        btn_stop: '停止 ⛔',
        
        lbl_x_max: 'X最大',
        lbl_y_max: 'Y最大',
        lbl_threshold: '阈值',
        lbl_border_margin: '边框边距',
        lbl_remove_borders: '移除边框',
        lbl_resolution: '分辨率',
        lbl_bidirectional: '双向',
        lbl_objects: '对象',
        lbl_width: '宽度',
        lbl_height: '高度',
        lbl_lock_ratio: '锁定比例',
        lbl_power: '功率',
        lbl_speed: '速度',
        lbl_passes: '次数',
        lbl_name: '名称',
        lbl_text: '文字',
        lbl_size: '大小 (mm)',
        lbl_lines: '行',
        
        ctx_set_home_here: '📍 在此设置原点',
        ctx_select: '✓ 选择',
        ctx_select_all: '☑ 全选',
        ctx_duplicate: '📋 复制',
        ctx_delete: '🗑️ 删除',
        ctx_center: '⊙ 居中',
        ctx_vectorize: '✏️ 矢量化',
        ctx_raster_gcode: '🖼️ 光栅G代码',
        ctx_edit_paths: '✂️ 编辑路径',
        ctx_gcode_vector: '📄 矢量G代码',
        ctx_simulate: '🎬 模拟',
        ctx_frame: '🔲 边框',
        ctx_go_home: '🏠 回原点',
        
        modal_new_preset: '新预设',
        modal_add_text: '添加文字',
        modal_gcode: '📄 G代码',
        
        tab_vector: '矢量',
        tab_raster: '光栅',
        
        sim_title: '🎬 模拟',
        sim_pos: '位置',
        sim_progress: '进度',
        sim_time: '时间',
        sim_mode: '模式',
        sim_speed: '速度',
        sim_mixed: '混合',
        
        tip_fit: '适应视图',
        tip_delete: '删除',
        tip_duplicate: '复制',
        tip_gcode: '生成G代码',
        tip_simulate: '模拟雕刻',
        tip_frame: '框选区域',
        tip_edit_paths: '编辑路径',
        
        status_connected: '已连接',
        status_disconnected: '未连接',
        status_ready: '就绪',
        
        msg_processing: '处理中...',
        msg_home_set: '原点已设置',
        msg_centered: '已居中',
        msg_select_vector: '请选择矢量',
        msg_path_deleted: '路径 #{n} 已删除',
        msg_small_paths_deleted: '已删除 {n} 个小路径',
        msg_object_deleted: '对象已删除',
        msg_duplicated: '已复制',
        msg_loaded: '已加载',
        msg_text_added: '文字已添加',
        msg_select_image: '请选择图片',
        msg_vectorizing: '矢量化中...',
        msg_no_contours: '未找到轮廓',
        msg_vectorized: '✅ 已矢量化: {n} 个轮廓',
        msg_no_objects: '没有对象',
        msg_gcode_generated: 'G代码 {mode}: {n} 行',
        msg_copied: '已复制！',
        msg_downloaded: '已下载！',
        msg_nothing_to_simulate: '没有可模拟的内容',
        msg_simulation_started: '模拟已开始:',
        msg_simulation_complete: '模拟完成',
        msg_simulation_stopped: '模拟已停止',
        msg_use_chrome: '请使用Chrome或Edge浏览器',
        msg_connected: '已连接',
        msg_disconnected: '已断开',
        msg_error: '错误',
        msg_emergency_stop: '⛔ 紧急停止',
        msg_not_connected: '未连接',
        msg_starting: '启动中...',
        msg_complete: '✅ 完成',
        msg_paused: '已暂停',
        msg_resumed: '已继续',
        msg_framing: '框选中...',
        msg_profile_saved: '配置已保存',
        msg_preset_applied: '预设已应用',
        msg_preset_saved: '预设已保存',
        msg_project_saved: '项目已保存',
        msg_project_loaded: '项目已加载',
        
        home_tip: '💡 右键点击 → "在此设置原点"',
        edit_mode_label: '✂️ 路径编辑器',
        editing: '编辑中',
        confirm_delete_all: '删除全部？'
    },

    // ==========================================
    // 日本語 (JAPANESE)
    // ==========================================
    ja: {
        _flag: '🇯🇵',
        _name: '日本語',
        
        sec_project: '📁 プロジェクト',
        sec_machine: '🔧 マシン',
        sec_home: '🏠 原点',
        sec_import: '📁 インポート',
        sec_vectorize: '✏️ ベクター化',
        sec_raster: '🖼️ ラスター',
        sec_path_editor: '✂️ パスエディター',
        sec_presets: '🎯 プリセット',
        sec_objects: '📦 オブジェクト',
        sec_properties: '⚙️ プロパティ',
        sec_jog: '🎮 ジョグ',
        
        btn_save: '💾 保存',
        btn_load: '📂 読込',
        btn_save_profile: '💾 プロファイル保存',
        btn_set: '📍 設定',
        btn_go: '🏠 移動',
        btn_import_image: '📷 画像/SVG',
        btn_add_text: '📝 テキスト',
        btn_vectorize: '🔄 ベクター化',
        btn_raster_gcode: '📄 ラスターGコード',
        btn_delete: '🗑️ 削除',
        btn_delete_small: '🧹 小さいパス',
        btn_new_preset: '+ 新規',
        btn_select_all: '全て',
        btn_clear: 'クリア',
        btn_start: '▶️ 開始',
        btn_pause: '⏸️ 一時停止',
        btn_resume: '▶️ 再開',
        btn_exit: '✓ 終了',
        btn_send: '送信',
        btn_copy: '📋 コピー',
        btn_download: '💾 ダウンロード',
        btn_send_machine: '📤 送信',
        btn_create: '✅ 作成',
        btn_connect: '接続',
        btn_disconnect: '切断',
        btn_stop: '停止 ⛔',
        
        lbl_x_max: 'X最大',
        lbl_y_max: 'Y最大',
        lbl_threshold: 'しきい値',
        lbl_border_margin: '境界マージン',
        lbl_remove_borders: '境界を削除',
        lbl_resolution: '解像度',
        lbl_bidirectional: '双方向',
        lbl_objects: 'オブジェクト',
        lbl_width: '幅',
        lbl_height: '高さ',
        lbl_lock_ratio: '縦横比固定',
        lbl_power: 'パワー',
        lbl_speed: '速度',
        lbl_passes: 'パス数',
        lbl_name: '名前',
        lbl_text: 'テキスト',
        lbl_size: 'サイズ (mm)',
        lbl_lines: '行',
        
        ctx_set_home_here: '📍 ここに原点を設定',
        ctx_select: '✓ 選択',
        ctx_select_all: '☑ 全て選択',
        ctx_duplicate: '📋 複製',
        ctx_delete: '🗑️ 削除',
        ctx_center: '⊙ 中央揃え',
        ctx_vectorize: '✏️ ベクター化',
        ctx_raster_gcode: '🖼️ ラスターGコード',
        ctx_edit_paths: '✂️ パス編集',
        ctx_gcode_vector: '📄 ベクターGコード',
        ctx_simulate: '🎬 シミュレート',
        ctx_frame: '🔲 フレーム',
        ctx_go_home: '🏠 原点へ移動',
        
        modal_new_preset: '新規プリセット',
        modal_add_text: 'テキスト追加',
        modal_gcode: '📄 Gコード',
        
        tab_vector: 'ベクター',
        tab_raster: 'ラスター',
        
        sim_title: '🎬 シミュレーション',
        sim_pos: '位置',
        sim_progress: '進捗',
        sim_time: '時間',
        sim_mode: 'モード',
        sim_speed: '速度',
        sim_mixed: '混合',
        
        tip_fit: 'ビューに合わせる',
        tip_delete: '削除',
        tip_duplicate: '複製',
        tip_gcode: 'Gコード生成',
        tip_simulate: '彫刻シミュレート',
        tip_frame: 'エリアをフレーム',
        tip_edit_paths: 'パス編集',
        
        status_connected: '接続済み',
        status_disconnected: '未接続',
        status_ready: '準備完了',
        
        msg_processing: '処理中...',
        msg_home_set: '原点を設定しました',
        msg_centered: '中央揃え完了',
        msg_select_vector: 'ベクターを選択してください',
        msg_path_deleted: 'パス #{n} を削除しました',
        msg_small_paths_deleted: '{n} 個の小さいパスを削除しました',
        msg_object_deleted: 'オブジェクトを削除しました',
        msg_duplicated: '複製しました',
        msg_loaded: '読み込みました',
        msg_text_added: 'テキストを追加しました',
        msg_select_image: '画像を選択してください',
        msg_vectorizing: 'ベクター化中...',
        msg_no_contours: '輪郭が見つかりません',
        msg_vectorized: '✅ ベクター化完了: {n} 個の輪郭',
        msg_no_objects: 'オブジェクトがありません',
        msg_gcode_generated: 'Gコード {mode}: {n} 行',
        msg_copied: 'コピーしました！',
        msg_downloaded: 'ダウンロードしました！',
        msg_nothing_to_simulate: 'シミュレートするものがありません',
        msg_simulation_started: 'シミュレーション開始:',
        msg_simulation_complete: 'シミュレーション完了',
        msg_simulation_stopped: 'シミュレーション停止',
        msg_use_chrome: 'ChromeまたはEdgeをご使用ください',
        msg_connected: '接続しました',
        msg_disconnected: '切断しました',
        msg_error: 'エラー',
        msg_emergency_stop: '⛔ 緊急停止',
        msg_not_connected: '未接続',
        msg_starting: '開始中...',
        msg_complete: '✅ 完了',
        msg_paused: '一時停止中',
        msg_resumed: '再開しました',
        msg_framing: 'フレーム中...',
        msg_profile_saved: 'プロファイルを保存しました',
        msg_preset_applied: 'プリセットを適用しました',
        msg_preset_saved: 'プリセットを保存しました',
        msg_project_saved: 'プロジェクトを保存しました',
        msg_project_loaded: 'プロジェクトを読み込みました',
        
        home_tip: '💡 右クリック → "ここに原点を設定"',
        edit_mode_label: '✂️ パスエディター',
        editing: '編集中',
        confirm_delete_all: '全て削除しますか？'
    }
};

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = LANG;
}